### ISSUE TITLE
hi, there is somethong wrong on windows 10, but I don't know how to fix it.

### ISSUE THREAD

**Issue by driftluo** [blackbeam/rust-mysql-simple#103]
I'm working on Win10 and the mysql version:
```
E:\>mysql --version
mysql  Ver 14.14 Distrib 5.7.13, for Win64 (x86_64)
```

this is my test code:
```
extern crate mysql;

// use mysql::{OptsBuilder, Opts};
use mysql::value::from_row;

fn main() {
	let pool = mysql::Pool::new("mysql://root:system@127.0.0.1:3306/example").unwrap();
	let result = pool.prep_exec("select ? * ?", (20i32, 0.8_f32)).unwrap();
	for row in result {
		let c: Option<f32> = from_row(row.unwrap());
		println!("{:?}", c);
	}
}
```
and the dependence:
```
[dependencies]
mysql = "*"
```
when I  try to complite it, there is something wrong:
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: DriverError { Could not connect to address `\\.\pipe\MySQL': 系统找不到指定的文件。 (os error 2) }', src\libcore\result.rs:859
note: Run with `RUST_BACKTRACE=1` for a backtrace.
error: process didn't exit successfully: `target\debug\mysql_read.exe` (exit code: 101)
```
I try to create a opts on myself:
```
let mut db = OptsBuilder::new();
db.ip_or_hostname(Some("127.0.0.1"))
    .db_name(Some("example"))
    .user(Some("root"))
    .pass(Some("system"))
    .tcp_port(3306);
```
the same error happened, so how can I do it?

**Comment by driftluo** [comment]
I once again read the document, found that the opts perfer_socket this property is the default open, I try to close it, then it can normal interaction with the mysql on Win, so the problem should be solved

**Comment by blackbeam** [comment]
Hi!

The problem here is that somehow the driver could not connect to the pipe address (\\.\pipe\MySql) reported by a server because there is no pipe with this address (i.e. server doesn't listen on the pipe it reports). I hope this problem is not related to every win10 mysql installations..

Anyway you can check that named-pipe is enabled in mysql configuration (there should be `enable-named-pipe` option in `[mysqld]` section of `my.ini`)

**Comment by driftluo** [comment]
There is no `enable-named-pipe` option in the file `my.ini`.
I don't enable the named-pipe on my computer, so it can't find the named-pipe, so I change the perfer_socket to `false`, then it can interact with tcp/ip.
But thanks for your answer@blackbeam

**Comment by anhhh11** [comment]
Change #enable-named-pipe to enable-named-pipe in my.ini works on XAMPP on Win10.
