### ISSUE TITLE
stmt will never close until the Pool is droped ?

### ISSUE THREAD

**Issue by fanvanzh** [blackbeam/rust-mysql-simple#105]
Hi, I am using your crate. 
I found "Com_stmt_close" var in mysql is never increase until the Pool is droped.
Is this the design ?
Here is the sql :
SHOW GLOBAL STATUS LIKE 'com_stmt%';

Here is my code : 

#[macro_use]
extern crate mysql;

fn test_mysql(pool: mysql::Pool){
    for _ in 0..100 {
        let mut conn = pool.get_conn().unwrap();
        for _ in 0..100 {
            let stmt = conn.prepare("select * from test.dsset").unwrap();
        }
    }
}

fn main() {
    let mysql_conn: String = format!(
        "mysql://{}:{}@{}:{}?prefer_socket=false",
        "root",
        "666666",
        "127.0.0.1",
        3306
    );
    let mut pool = mysql::Pool::new(mysql_conn.as_str()).unwrap();
    pool.use_cache(false);
    test_mysql(pool.clone());
    loop {
        std::thread::sleep_ms(1000);
    }
    return;
}

**Comment by blackbeam** [comment]
Hi!

> Is this the design?

No. It's definitely a flaw. I'll fix it right after my vacation.

Thanks for report!

**Comment by blackbeam** [comment]
Fixed in
