### ISSUE TITLE
Example select with params.

### ISSUE THREAD

**Issue by glennpierce** [blackbeam/rust-mysql-simple#107]
Hi

Can someone please add a simple example of how to do a select query with parameters ?

ie

Here TIMESTAMP is a numeric i64 (milliseconds)

pool.prep_exec("SELECT HISTORY_ID, TIMESTAMP, STATUS_TAG from HISTORYNUMERICTRENDRECORD WHERE TIMESTAMP >= :end_dt", (&end_dt))

I can't find an example and at the moment get the error

    |                      ^^^^^^^^^ the trait `std::convert::From<i64>` is not implemented for `mysql::Params` 

Thanks

**Comment by blackbeam** [comment]
Hi!

To pass named parameters (`:end_dt` in your case) to a statement you should use `params!` macro (make sure that mysql crate is imported with `#[macro_use]` annotation):
``` rust
pool.prep_exec(
    r"SELECT HISTORY_ID, TIMESTAMP, STATUS_TAG
    from HISTORYNUMERICTRENDRECORD WHERE TIMESTAMP >= :end_dt",
    params! { "end_dt" => end_dt }
);
```

To pass single positional parameter to a statement you must pass it as a tuple, for example `(end_dt,)`. Note trailing comma here. It states that it is single value tuple and not just value in parentheses (see docs for [Stmt::execute](http://blackbeam.org/doc/mysql/struct.Stmt.html#method.execute)):
```rust
pool.prep_exec(
    r"SELECT HISTORY_ID, TIMESTAMP, STATUS_TAG
    from HISTORYNUMERICTRENDRECORD WHERE TIMESTAMP >= ?",
    (end_dt,)
);
```

**Comment by philippludwig** [comment]
This should be part of the documentation, if not even the very first you see there - select-from-where queries are the most important thing in MySQL and I had no clue how to do them with this driver until I found this issue.

Now if only someone could explain how to use a `String` or a `str` parameter.
