### ISSUE TITLE
Recent versions cannot be co-installed with byteorder 1.1

### ISSUE THREAD

**Issue by living180** [blackbeam/rust-mysql-simple#108]
This crate depends on `byteorder = ~1.0`.  This means that when byteorder 1.1 was released, the following combination in Cargo.toml caused mysql to be downgraded to version 8.0.0:

    [dependencies]
    byteorder = "1"
    mysql = "*"

I recommend changing mysql to depend on `byteorder = "1"` which would resolve this issue.

**Comment by blackbeam** [comment]
Thanks for report.
Fixed in v11.3.1
