### ISSUE TITLE
Value#into_str with version 12+

### ISSUE THREAD

**Issue by cars10** [blackbeam/rust-mysql-simple#110]
Hi, with version 11.x i did something like:

```rust
let values = mysql::Row::unwrap(row.unwrap());
let str_values: Vec<String> = values.iter().map(|v| v.into_str()).collect();
```

How would i do that with version 12? I would like to have the values of a row as `str` or `String`.

**Comment by blackbeam** [comment]
Ah! I forgot to update documentation.
Please use [Value::as_sql](http://blackbeam.org/doc/mysql/enum.Value.html#method.as_sql)

**Comment by cars10** [comment]
Thanks! Works fine now.
