### ISSUE TITLE
Connect via SSH tunnel

### ISSUE THREAD

**Issue by cars10** [blackbeam/rust-mysql-simple#111]
Hi, is it possible to connect via ssh tunnel to a mysql server?
If so - could you please give an example?

**Comment by blackbeam** [comment]
Hi!

It has ssl support only for Linux and Mac OS.
Which of this do you use?

**Comment by cars10** [comment]
I am on linux.

**Comment by blackbeam** [comment]
You can look into mysql::conn::test::get_opts implementation for examles.
Implementation under `#[cfg(all(feature = "ssl", target_os = "macos"))]` is for Mac OS,
and under `#[cfg(all(feature = "ssl", not(target_os = "macos"), unix))]` is for other unix-like platforms (based on openssl).

**Comment by cars10** [comment]
Hm, not sure if that helps me. I am looking to do basically the same thing that mysql-workbench and other tools do, connect to a mysql server on a different host via ssh. See the following image for example:

![image](https://user-images.githubusercontent.com/4118628/28911115-c540f4b0-782f-11e7-8776-d2178c0d4aeb.png)

**Comment by blackbeam** [comment]
Oh, damn! I messed up with `ssl` vs `ssh` (need more sleep).

No driver-side support required. You only need to [open ssh tunnel](http://blog.trackets.com/2014/05/17/ssh-tunnel-local-and-remote-port-forwarding-explained-with-examples.html) yourself (i'm sure this is what mysql-workbench do for you).
