### ISSUE TITLE
the trait `mysql::prelude::FromValue` is not implemented for `chrono::DateTime<chrono::Local>`

### ISSUE THREAD

**Issue by zyfmix** [blackbeam/rust-mysql-simple#118]
when i fetch table field with type datetime like below:
CommonAccountInfoModel struct:
``` rust
#[derive(Debug, PartialEq, Serialize, Deserialize)]
pub struct CommonAccountInfoModel {
    #[serde(rename = "aiId")]
    pub ai_id: u64,
    #[serde(rename = "aInfoName")]
    pub a_info_name: String,
    #[serde(rename = "aInfoPhone")]
    pub a_info_phone: String,
    #[serde(rename = "lastLogin")]
    //pub last_login: Option<chrono::prelude::NaiveDateTime>,
    pub last_login: Option<chrono::prelude::DateTime<chrono::Local>>,
}
```
my rust code:
``` rust
pub fn query_common_account_info_list(pool: &mysql::Pool, query_sql: &str) -> Vec<models::CommonAccountInfoModel> {
    // Let's select payments from database
    let mut selected_account_list: Vec<models::CommonAccountInfoModel> =
        pool.prep_exec(query_sql, ())
            .map(|result| {
                result.map(|x| x.unwrap()).map(|mut row| {
                    models::CommonAccountInfoModel {
                        ai_id: row.take("aiId").unwrap(),
                        a_info_name: row.take("aInfoName").unwrap(),
                        a_info_phone: row.take("aInfoPhone").unwrap(),
                        last_login: row.take("lastLogin").unwrap(),
                        //last_login: DateTime::from_utc(NaiveDateTime::from_timestamp(lastLogin.sec, lastLogin.nsec), ...),
                    }
                }).collect()
            }).unwrap();

    while let Some(top) = selected_account_list.pop() {
        // Prints 3, 2, 1
        println!("##########{:?}", top);
        println!("##########{}", top.ai_id);
    }

    selected_account_list
}
```
when i exe cargo run,it show me error:
``` bash
Tue Sep 12 10:40:43 yzhang@ms:~/Dev/Rust/zs_ms$ cargo run
   Compiling zs_ms v0.1.0 (file:///data/home/yzhang/Dev/Rust/zs_ms)

error[E0277]: the trait bound `chrono::DateTime<chrono::Local>: mysql::prelude::FromValue` is not satisfied
  --> src/mysql_qs.rs:93:41
   |
93 |                         last_login: row.take("lastLogin").unwrap(),
   |                                         ^^^^ the trait `mysql::prelude::FromValue` is not implemented for `chrono::DateTime<chrono::Local>`
   |
   = note: required because of the requirements on the impl of `mysql::prelude::FromValue` for `std::option::Option<chrono::DateTime<chrono::Local>>`

error: aborting due to previous error(s)

error: Could not compile `zs_ms`.
Build failed, waiting for other jobs to finish...
error: build failed
```
i wanna get last_login value with type chrono::prelude::DateTime< chrono::Local >,how can i fixed it?

**Comment by blackbeam** [comment]
Hi!

Mysql's datetime is naive. `FromValue` is implemented for `chrono::NaiveDateTime` so you should first convert row value to `chrono::NaiveDateTime` and then convert `chrono::NaiveDateTime` to `chrono::DateTime<chrono::Local>`.
Please look into [documentation](https://dev.mysql.com/doc/refman/5.6/en/datetime.html) on date, datetime and timestamp types.
Also note that naivedatetime returned from mysql's datetime column will most likely be in the timezone that was specified in mysql's [`time_zone`](https://dev.mysql.com/doc/refman/5.5/en/time-zone-support.html) setting at the moment of writing datetime to the table.

**Comment by realwhz** [comment]
Sorry to comment on this closed old issue.  It is 2022 now and I encountered the same error.  Google search directed me here but the root cause and solution are different.  It turns out that the implementation of `FromValue` is moved to `mysql_common`.  Unfortunately, chrono is not enabled by default.  So a solution is to turn it on in `mysql_common`.
```
[dependencies.mysql_common]
features = ["chrono"]
```

**Comment by blackbeam** [comment]
@realwhz, thanks!

Let me put here a few helpful links:
1. List of `mysql_common` features – https://github.com/blackbeam/rust_mysql_common#crate-features
2. Some caviats regarding `mysql_common` features – https://github.com/blackbeam/rust-mysql-simple#crate-features

**Comment by morugetsm** [comment]
I also encountered this problem and found solution after a lot of searching.
I think trouble shooting for this might be written in somewhere but I want to share this in here for another people like me.

1. If you want to use this crate with chrono, you have to add mysql_common with chrono feature.
2. The important thing is you have to install exact same version of mysql crate's dependency version of mysql_common crate.
3. For example, the newest version of mysql crate is 22.2.0 that dependents on mysql_common 0.28.2. But, the newest version of mysql_common crate is 0.29.1.
4. So if you just add mysql_common by using 'cargo add', it will install incompatible version and your code would not be compiled.
5. When you add mysql crate to your project, you can find which version of mysql_common is needed for current version of mysql by searching 'mysql_common' in Cargo.lock
6. For now(2022-10-28), the solution is...
```
cargo add mysql_common@0.28.2 --features chrono
```

**Comment by Elcoid** [comment]
Just an addendum to @realwhz's answer:

I encountered the same problem today and @realwhz's answer helped a lot, however the following warning was issued:
`
warning: dependency (mysql_common) specified without providing a local path, Git repository, version, or workspace dependency to use. This will be considered an error in future versions
`

I was able to remove it by specifying in Cargo.toml that any version is fine:
```
[dependencies.mysql_common]
version = "*"
features = ["chrono"]
```
