### ISSUE TITLE
How to generate prepare statement dynamic

### ISSUE THREAD

**Issue by linpingchuan** [blackbeam/rust-mysql-simple#138]
Hi,
Now I had a problem about generate prepare statement.

Could you give me some develop document about generate prepare statement dynamic by rust-mysql-simple?

Thanks

**Comment by blackbeam** [comment]
Hi!

You mean some kind of a query builder for mysql? `rust-mysql-simple` does not have one, unfortunately. It's a bit out of scope for the database driver.

**Comment by linpingchuan** [comment]
Get it. :smiley_cat:
