### ISSUE TITLE
Can the flag CLIENT_FOUND_ROWS be forced

### ISSUE THREAD

**Issue by n3m4nja** [blackbeam/rust-mysql-simple#142]
Hi,

I was using the library and noticed when performing UPDATES affected row always matches changed rows and not matched rows. I managed to get the desired behaviour when placing this flag in the`get_client_flags` connection method, but I haven't found any other way to force this.

Is there a way to selectively pass this flag when establishing connection?

Thanks

**Comment by blackbeam** [comment]
Support added in v13.0.0. Please see the [release notes](https://github.com/blackbeam/rust-mysql-simple/releases/tag/v13.0.0).

**Comment by n3m4nja** [comment]
Great! Thx!

**Comment by n3m4nja** [comment]
One thing regarding this fix. Compiler is complaining about the constant in the CapabilityFlags not being public. Code works regardless, but I am not sure if it is a valid compiler complaint or not.

Cheers!
