### ISSUE TITLE
Client does not support authentication protocol requested by server

### ISSUE THREAD

**Issue by jendakol** [blackbeam/rust-mysql-simple#143]
Hi,
I have an application using your client. During development I've been using locally MariaDB and everything was ok. Now I implement integration tests using docker-compose and use `mysql:latest` (which means 8.x)  which causes me troubles. The connection to the server fails with message:
```
ERROR 1251 (08004): Client does not support authentication protocol requested by server; consider upgrading MySQL client
```
From docs I've understood it's a problem of client which doesn't support new authentication scheme presented in MySQL 4.1. Could you please implement support for it? I'd like to help but don't know how.
Thx.

**Comment by jendakol** [comment]
`mysql = { version = "~12.1", features = ["ssl"] }`
Just noticed there is already version 13. Should it work with the new one?
Unfortunately upgrade to 13.0 causes me some troubles, so I'm unable to try it currently.

**Comment by blackbeam** [comment]
Oh!
I see that in MySql 8 default password mechanism is changed to `caching_sha2_password` and library only supports `mysql_native_password`, which is default mechanism for previous MySql versions. So I'll work on implementing `caching_sha2_password` mechanism.
Until then your only option is to reconfigure your MySql8 instance to use legacy `mysql_native_password`.

For more info please see https://mysqlserverteam.com/mysql-8-0-4-new-default-authentication-plugin-caching_sha2_password/
