### ISSUE TITLE
openssl depency seems broken

### ISSUE THREAD

**Issue by ProcTrap** [blackbeam/rust-mysql-simple#15]
failed to run custom build command for openssl-sys v0.6.0  
    fatal error: openssl/hmac.h: No such file or directory`
    panicked at 'explicit panic' .. src/lib.rs:380

With dault-features = false it's working.

Opened for further upgrading to a new lib version & just in case sb other also receives this error.

**Comment by blackbeam** [comment]
I know that mysql did not build tonight because of api change in openssl 0.6.0 and i will fix this asap.
But in your case it looks like there is something with openssl's C headers availability on your platform.

**Comment by ProcTrap** [comment]
Hm, could be, cause it's a vm just for server tests.
Do I need to install the openssl dev package ?

**Comment by blackbeam** [comment]
You definitely need openssl dev for headers.

mariadb? hmm.. maybe )

**Comment by ProcTrap** [comment]
Yep, apt-get install libssl-dev fixed the missing files error.

(http://mariadb.org/ just in case sb shouldn't know it )

**Comment by blackbeam** [comment]
That's great.
Fix for openssl 0.6.0 is also ready and published on crates.io as mysql 0.8.1.
