### ISSUE TITLE
Please write about breaking changes

### ISSUE THREAD

**Issue by e-oz** [blackbeam/rust-mysql-simple#151]
There is no way to upgrade from 11.3 to 14.
Changelog is empty - 0 breaking changes mentioned, when API is changed significantly.
I tried to find where is from_row_opt now and couldn't find it, I'm giving up.

**Comment by blackbeam** [comment]
Hi. All significant updates are listed [here][2], but breaking changes are not highlighted in any way, so sorry about that.

BTW, what's with [from_row_opt][1]?

[1]: https://docs.rs/mysql/14.0.0/mysql/fn.from_row_opt.html
[2]: https://github.com/blackbeam/rust-mysql-simple/releases

**Comment by e-oz** [comment]
Breaking changes are not even listed there. Module "value" has been removed, enum `value` has been renamed to `Value`, etc. 
Anyway, it was just single complain. Thank you for your work, anyway :)
