### ISSUE TITLE
how to use params! with vec

### ISSUE THREAD

**Issue by softprops** [blackbeam/rust-mysql-simple#153]
a common query case is selecting from a table where a column contains 1 or more values

```
select * from mytable where myfield in (:ids)
```

however there doesn't seem to be a convention for types I think are supported a usize contained in Vec types. 

```
78 |                             params!("ids" => my_vec),
   |                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `std::convert::From<std::vec::Vec<usize>>` is not implemented for `mysql::Value`
   |
   = help: the following implementations were found:
             <mysql::Value as std::convert::From<[u8; 23]>>
             <mysql::Value as std::convert::From<mysql::<unnamed>::NaiveDateTime>>
             <mysql::Value as std::convert::From<mysql::<unnamed>::Timespec>>
             <mysql::Value as std::convert::From<crowbar::Value>>
```

Is this currently possible and if so whats the write way to express this kind of query

**Comment by blackbeam** [comment]
Hi.

Single `?` in a prepared statement is a placeholder for a single mysql value, and, unfortunately, there is no such value as _vector of something_ in mysql binary protocol.

What you need, is a query builder, but this crate doesn't have one because it's out of scope for a database driver.

**Comment by softprops** [comment]
I'm looking for something light. Do you know if something like a small query builder for mysql exists? I'm not looking for a full on orm  orm like diesel but instead a lean way to talk to mysql and extract row data

**Comment by blackbeam** [comment]
> Do you know if something like a small query builder for mysql exists?

No, unfortunately. But building one is, usually, a trivial task. At least for dinamic languages 😀.
