### ISSUE TITLE
Problem with parallel tests & muliple statements

### ISSUE THREAD

**Issue by 0xpr03** [blackbeam/rust-mysql-simple#154]
Hello,
I'm having trouble testing a multi-statement struct.
I have a stream of elements and for each I have to execute two Statements.
All of my existing functions are written to work with a &mut PooledConn because my tests will create a virtual table, so each of them can (as per cargo) run parallel without sharing data.
As you specified yourself you expect people to use a pool for multiple statements, but because of the threading of my tests I can't use a pool.
Is there a better approach or am I missing something ?
This approach here is un-testable as the pool will give each one another connection ( and block the test indefinitely when I force a 1min, 1max pool)
```rust
pub struct ImportAccountInserter<'a> {
    stm_member_names: Stmt<'a>,
    stm_member_addition: Stmt<'a>,
    comment_addition: &'a str,
    date_name_insert: &'a NaiveDateTime
}

impl<'a> ImportAccountInserter<'a> {
    /// New Import Account Inserter
    /// comment_addition: appended to comment on insertion (`imported account`)
    /// date_name_insert: date to use for name insertion & update field
    pub fn new(pool: &'a Pool, comment_addition: &'a str, date_name_insert: &'a NaiveDateTime) -> Result<ImportAccountInserter<'a>,Error> {
        Ok(ImportAccountInserter {
            stm_member_names: pool.prepare("INSERT IGNORE INTO `member_names` (`id`,`name`,`date`,`updated`) VALUES (?,?,?,?)")?,
            stm_member_addition: pool.prepare("INSERT IGNORE INTO `member_addition` (`id`,`name`,`vip`,`comment`) VALUES (?,?,?,?)`")?,
            comment_addition,
            date_name_insert
        })
    }
    
    pub fn insert_account(&mut self, acc: &import::ImportAccount) -> Result<(),Error> {
        self.stm_member_names.execute((acc.id,&acc.name,self.date_name_insert,self.date_name_insert
        ))?;
        self.stm_member_addition.execute((acc.id,&acc.vname,acc.vip,
            format!("{}{}",self.comment_addition,acc.comment)
        ))?;
        Ok(())
    }
}
```

Regards, 0xpr03

Edit: sorry, currently on the train

**Comment by blackbeam** [comment]
Hi!
By virtual table you mean `CREATE TEMPORARY TABLE ..`? IIUYC, then you need to get one connection per your parallel test and execute statements on it using `prep_exec`.

**Comment by 0xpr03** [comment]
Yes I mean `CREATE TEMPORARY TABLE`, prep_exec would make it possible that the temporary tables are created but in my example above the data would be scattered between two threads. And I'd have to be lucky to get the exact same threads for testing again.

1. create temporary table
2. do something like inserting data
3. test against inserted data (existing? /changed ? ..)

Which would require to be on the same connection.

**Comment by 0xpr03** [comment]
Current approach (without the feature for which I want to use two prepared statements) can be seen here: https://github.com/0xpr03/clantool/blob/master/src/db.rs#L353

**Comment by blackbeam** [comment]
> As you specified yourself you expect people to use a pool for multiple statements

There is no such limitation. You can use `prep_exec` to prepare/run multiple statements on a single `Conn` (prepared statements will fall into connection's statement cache. see #57, #39).

Temporary tables are seen only within connections they was created and `Pool` gives no guaranties on which connection will be returned from it. If you want to use temporary table within your test, then you need to create one `Conn` or `PooledConn` and use only this connection within your test.

If you want to use a singe connection with temporary table created in it within multiple threads, then you need to store it somewhere and you need a way to syncronize access to it.

**Comment by blackbeam** [comment]
> The limitation I meant was that you have to use a Pool if you want more then one statement at a time, you can't use a single connection to create multiple statements at once.

Each first call to prepare or prep_exec prepares a statement and stores it inside the connection. Subsequent calls will use already prepared statements. API won't let you to get multiple statements from single connection at a time because in either case you can't execute them or even iterate the result in parallel because of a mysql protocol limitation.

I suggest you to use single `Conn` and multiple calls to `prep_exec` instead of multiple `Stmt`s. It is equivalent to desired "multiple statements on a single connection" and also it's the only option for you because of a temporary table.

**Comment by 0xpr03** [comment]
That is unfortunate as this renders my performance pretty bad. Also: either way I can't use the pool statement cache, as I've to get a connection first (and the pool doesn't know for which purpose).
I guess I'll have to stick with manual connections as per my first idea or force all Database tests to run one after another.

**Comment by blackbeam** [comment]
There is not such thing as "pool statement cache". It's just a cache of all connections within a pool.
That's because prepared statements exists only within connections they was prepared. Just like temporary tables.

Pool does not have a mechanism to track existence of temporary tables in connections so you either have to stick with manual connections or have to run `CREATE TEMPORARY TABLE IF NOT EXISTS ..` on every connection taken from a pool.

I think if you set your pool min/max to a number of parallel tests, then your pool either give you connection with your statements prepared or give you a new connection because other is taken by parallel test. For me it looks like best approach in terms of performance.

> That is unfortunate as this renders my performance pretty bad.

By the way, which missing driver feature, you think, will save your performance?

**Comment by 0xpr03** [comment]
> Pool does not have a mechanism to track existence of temporary tables in connections so you either have to stick with manual connections or have to run CREATE TEMPORARY TABLE IF NOT EXISTS .. on every connection taken from a pool.

My problem is not creating virtual tables. My problem is that I need the exact same connection afterwards to test against the result in the database. Because every other connection won't see that change, as per definition of a virtual table.

> By the way, which missing driver feature, you think, will save your performance?

Non driver feature related: I'll have to adopt serial tests or do a multi-pass of my data, so I'm using only one statement at a time. Or load all data into RAM and then serially do the database operation.

[souce](https://docs.rs/mysql/12.3.1/mysql/struct.Pool.html#method.use_cache)
> [..] will search for cached statement through all connections in the pool

Even without the problem above I will loose the gain of that feature at all other places, where I use a statement, as all statements are done on the same connection.
```
forever {
 {Statement A }
 {Statement B }
}
```
As I use the same connection, instead of a pool, I will have to re-create both statements over and over in my application. If A & B would be on different connection through the pool, both could be re-used, Statement A & B would be prepared only once, and their connection re-used afterwards.

I am currently evaluating to create persistent tables using a naming scheme of table-name + thread ID

**Comment by 0xpr03** [comment]
I solved it for now using a drop-guard which cleans up the Database & owns the pool, as well as using explicit `cargo test -- --test-threads=1`
