### ISSUE TITLE
Transactions & Statements in the same structure

### ISSUE THREAD

**Issue by 0xpr03** [blackbeam/rust-mysql-simple#155]
Hello,
I've tried to do create a struct that is basically an abstraction for streaming data and is set to commit at the end.
Here a simple example with only one statement and one transaction:
```rust
pub struct MyStruct<'a> {
    transaction: Transaction<'a>,
    stm: Stmt<'a>
}

impl<'a> MyStruct<'a> {
    pub fn new(pool: Pool) -> MyStruct<'a>{
        let tr = pool.start_transaction().unwrap();
        MyStruct {
         transaction: tr,
         stm: tr.prepare("INSERT INTO table (col) VALUES (?)").unwrap()
        }
    }

    // called by data loop
    pub fn use(&mut self, data: &i32) {
        self.stm.execute((data,)).unwrap();
    }

    // called at the end
    pub fn commit() {
        self.transaction.commit().unwrap();
    }
}

fn main() {
    let pool = ..
    let mut my_struct = MyStruct::new(pool);
    for i in 0..100 {
        my_struct.use(&i);
    }
    my_struct.commit();
}
```

```
error[E0597]: `tr_1` does not live long enough
        stm: tr.prepare("INSERT INTO table
    |           ^^^ borrowed value does not live long enough
```

If I move it around, I'm "moving" the transaction after creating the statement.

And another bug:

```
error[E0507]: cannot move out of borrowed content
        self.transaction.commit()?;
    |         ^^^^ cannot move out of borrowed content
```

I've talked to several people on IRC and was told that the mysql crate prevents this from working.
I'd really like to use the connection in the way described above, as this allows for a much better streaming system, easier testing and better handling overall. The current implementation of mysql-simple doesn't allow this.

**Comment by blackbeam** [comment]
Hi

Please do not use `Stmt` at all. I will remove it in next version to avoid confusion.
There is literally no performance difference between the following approaches:

```rust
#[bench]
fn prep(bencher: &mut test::Bencher) {
    let mut conn = Conn::new(get_opts()).unwrap();

    let value: String = ::std::iter::repeat('A').take(40).collect();
    let mut stmt = conn.prepare("SELECT ?").unwrap();

    bencher.iter(|| {
        let _ = stmt.execute((&value,));
    });
}

#[bench]
fn prep_exec(bencher: &mut test::Bencher) {
    let mut conn = Conn::new(get_opts()).unwrap();

    let value: String = ::std::iter::repeat('A').take(40).collect();

    bencher.iter(|| {
        let _ = conn.prep_exec("SELECT ?", (&value,));
    });
}
```

```
test conn::test::bench::prep                                          ... bench:      32,937 ns/iter (+/- 12,673)
test conn::test::bench::prep_exec                                     ... bench:      32,232 ns/iter (+/- 12,596)
```

Please rewrite your code in the following way:

```rust
pub struct MyStruct<'a> {
    transaction: Transaction<'a>,
}

impl<'a> MyStruct<'a> {
    pub fn new(pool: Pool) -> MyStruct<'a>{
        let tr = pool.start_transaction().unwrap();
        MyStruct {
         transaction: tr,
        }
    }

    // called by data loop
    pub fn use(&mut self, data: &i32) {
        self.transaction.prep_exec("INSERT INTO table (col) VALUES (?)", (data,)).unwrap();
    }

    // called at the end
    pub fn commit() {
        self.transaction.commit().unwrap();
    }
}

fn main() {
    let pool = ..
    let mut my_struct = MyStruct::new(pool);
    for i in 0..100 {
        my_struct.use(&i);
    }
    my_struct.commit();
}
```

**Comment by 0xpr03** [comment]
> Please do not use Stmt at all. I will remove it in next version to avoid confusion.
> There is literally no performance difference between the following approaches:

Thanks for the help. I got your idea now and changed my approach and understood now why I can directly use the Transaction.
What I don't get is there a performance penalty on using one Transaction for multiple different queries instead of using one Transaction per query ? 
`This call will take statement from cache if has been prepared on this connection.`
So it could be irrelevant to use multiple transactions for overlapping queries.
```rust
// called by data loop
pub fn use(&mut self, data: SomeStruct) {
    self.transaction.prep_exec("INSERT INTO A (col) VALUES (?)", (data.a,)).unwrap();
    self.transaction.prep_exec("INSERT INTO B (col) VALUES (?)", (data.b,)).unwrap();
    self.transaction.prep_exec("INSERT INTO C (col) VALUES (?)", (data.c,)).unwrap();
}
```
or
```rust
// called by data loop
pub fn use(&mut self, data: SomeStruct) {
    // note one transaction per different, repetitive called query
    self.transaction_1.prep_exec("INSERT INTO A (col) VALUES (?)", (data.a,)).unwrap();
    self.transaction_2.prep_exec("INSERT INTO B (col) VALUES (?)", (data.b,)).unwrap();
    self.transaction_3.prep_exec("INSERT INTO C (col) VALUES (?)", (data.c,)).unwrap();
 }
```

And how do I solve the problem of commit() (for the approach of one transaction per query I really want to have one commit function)
```
error[E0507]: cannot move out of borrowed content
        self.transaction.commit()?;
    |         ^^^^ cannot move out of borrowed content
```

**Comment by 0xpr03** [comment]
Currently trying `Option<Transaction>` for `commit()` but that has the overhead of `.unwrap()` requirements before any `prep_exec` in `use()`

**Comment by blackbeam** [comment]
> What I don't get is there a performance penalty on using one Transaction for multiple different queries instead of using one Transaction per query ?

Transaction always implies overhead over direct write at least for roundtrips to start and commit/rollback it. And whether it should be used or not (and how many transactions should be used) is not a question of performance but a question of whether this primitive is required to achieve your goal.

> And how do I solve the problem of commit() (for the approach of one transaction per query I really want to have one commit function).

`Transaction::commit()` consumes transaction so you either should leave off the ownership of transaction (for `Option<Transaction<'_>>` it would be `take()`) or consume your struct in `MyStruct::commit`. Decision, obviously, depends on whether your struct needs to be used after commit or not.

**Comment by 0xpr03** [comment]
> Transaction always implies overhead over direct write at least for roundtrips to start and commit/rollback it

I meant: Are statements re-used when I use one transaction for everything or do I need to use multiple transactions because one transaction also implies only being able to cache one statement.
=> Can one transaction cache multiple statements (created via prep_exec ), or do I need to use multiple statements for that, because one statement can only cache one (the last used) statement.
I'm aware this is kinda nit picking but I'm really interested in making the right choice.

I'll try to use the idea of leaving off the lifetime.
Consuming my struct isn't possible when I use multiple transaction, is it? (Which depends on the answer for my question above.)

I hope this issue also helps other people with similar issues in the future.

**Comment by 0xpr03** [comment]
Ah I guess I've made the wrong assumption about transactions being bundled with connection which in turn can only cache one (the last) prepared statement.
As in all other languages you definitely have some kind of binding between this.
Thanks for your information and the help!
