### ISSUE TITLE
entered unreachable code

### ISSUE THREAD

**Issue by nnovikov** [blackbeam/rust-mysql-simple#161]
I try to use mysql crate in my project, write primitive example and have panic:
thread 'main' panicked at 'internal error: entered unreachable code', /home/nnovikov/.cargo/registry/src/github.com-1ecc6299db9ec823/mysql-14.1.1/src/conn/mod.rs:1131:21

Is it a bug or I do something wrong?

**Comment by nnovikov** [comment]
I think the problem is in handling auth_plugin in HandshakePacket
Here it may be set to None if not found in received packet:
https://github.com/blackbeam/rust_mysql_common/blob/master/src/packets.rs#L853
But here
https://github.com/blackbeam/rust-mysql-simple/blob/master/src/conn/mod.rs#L1131
None is a way to unreachable code block.

**Comment by blackbeam** [comment]
Hi.

Looks like your mysql version is quite old. Which mysql version do you use?

**Comment by nnovikov** [comment]
I use custom mysql-proxy with our mysql protocol implementation.

**Comment by blackbeam** [comment]
Oh! Interesting.

According to the [documentation][1] handshake packet contains auth-plugin name only if `CLIENT_PLUGIN_AUTH` capability is set and `CLIENT_PLUGIN_AUTH` is always set for relatively newclients.

It looks like, however, that driver should fall back to mysql_native_password in case of no auth-plugin name in an initial handshake packet. I'll fix it.

Thanks for report!

[1]: https://dev.mysql.com/doc/internals/en/connection-phase-packets.html#packet-Protocol::Handshake

**Comment by nnovikov** [comment]
All wokrs fine now. Big thanks!
