### ISSUE TITLE
On 15.0 compilation error using default-features false

### ISSUE THREAD

**Issue by 0xpr03** [blackbeam/rust-mysql-simple#168]
Hello,
I've upgraded from 11.1 to 15.0 and hit the folliwing error using `default-features = false`

```
error[E0463]: can't find crate for `myc`
   --> /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/mysql-15.0.0/src/lib.rs:140:1
    |
140 | extern crate mysql_common as myc;
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ can't find crate

error: aborting due to previous error
```

Without this flag everything compiles. It's not very urgent as I'm also fine without that flag and am not sure if it's event correct to use it anyway.

**Comment by blackbeam** [comment]
Hi.

You must choose at least one of existing feature sets for `mysql_common` to become available with correct features. It was made optional to allow specifying `rustc_serialize` feature [here](https://github.com/blackbeam/rust-mysql-simple/blob/master/Cargo.toml#L46).

I.e. `mysql_common` dependency specified as optional but actually it's mandatory.
