### ISSUE TITLE
implement select_db()

### ISSUE THREAD

**Issue by jbmcgill** [blackbeam/rust-mysql-simple#170]
The MySQL protocol defines COM_INIT_DB / 0x02 as "change the default schema of the connection" [1]. It is used by the MySQL CLI when doing a "USE db" statement and is implemented in the c client as:
 
    int mysql_select_db(MYSQL * mysql,
                         const char * db);

Would you consider accepting a pull request for this feature?

[1] https://dev.mysql.com/doc/internals/en/com-init-db.html

**Comment by blackbeam** [comment]
Hi.

**Comment by blackbeam** [comment]
Was preliminary closed by accident 😅

**Comment by jonhoo** [comment]
@blackbeam can we get a minor release of this for https://github.com/jonhoo/msql-srv/pull/6 ?

**Comment by blackbeam** [comment]
Hi. Published as [v15.1.0][1]

[1]: https://github.com/blackbeam/rust-mysql-simple/releases/tag/v15.1.0
