### ISSUE TITLE
Convert OptionsBuilder into Opts for connection

### ISSUE THREAD

**Issue by klarinetkid** [blackbeam/rust-mysql-simple#173]
I can't figure this out. I have an optionsbuilder struct but I can't pass it to Conn::new. 

```
 let builder = OptsBuilder::new()
        .ip_or_hostname(Some("localhost"))
        .db_name(Some("db"))
        .user(Some("user"))
        .pass(Some("password"));

   mysql::Conn::new(builder)

mysql::Conn::new(builder)
        ^^^^^^^^^^^^^^^^ the trait `std::convert::AsRef<str>` is not implemented for `mysql::conn::opts::OptsBuilder`

```

I can't find any method or trait on OptionsBuilder into Opts.

**Comment by blackbeam** [comment]
Hi.

The problem is that [`OptsBuilder::pass`](https://docs.rs/mysql/15.1.0/mysql/struct.OptsBuilder.html#method.pass) returns `&mut OptsBuilder` but you need `OptsBuilder`.
The error message, however, is quite misleading.

**Comment by wucke13** [comment]
@blackbeam This should be stated more clearly in the documentation. I searched multiple hour to find this.

**Comment by dangoodman** [comment]
Having the same problem. So, how it's supposed to convert `&mut OptsBuilder` to `Opts`?

**Comment by blackbeam** [comment]
Hi, @dangoodman.

Please note, that the current README.md if for the future version (not yet released). You should look into the [crate docs](https://docs.rs/mysql/17.0.0/mysql/struct.OptsBuilder.html).

**Comment by dangoodman** [comment]
Thank you for the fast response.

Yes, looking at the crate docs. However, for noobies like me it didn't look clear that you must use a temporary mut variable for a builder before setting it up.

```rust
// the trait `std::convert::AsRef<str>` is not implemented for `mysql::opts::OptsBuilder`
let pool = mysql::Pool::new(OptsBuilder::new().user(Some("root")));
```

vs

```rust
// works
let mut builder = OptsBuilder::new();
builder.user(Some("root"));
let pool = mysql::Pool::new(builder);
```
