### ISSUE TITLE
How to handle error when having a bad DSN

### ISSUE THREAD

**Issue by nbari** [blackbeam/rust-mysql-simple#178]
Hi, any example about how to prevent panicking when using a bad DSN, more here: https://stackoverflow.com/q/56869746/1135424

```
let mut opts = mysql::OptsBuilder::from_opts(dsn);
opts.stmt_cache_size(0);
let pool = mysql::Pool::new_manual(1, 3, opts).expect("Could not connect to MySQL");
```

If I pass an invalid DSN, the code panics:
    
    thread 'main' panicked at 'URL ParseError { relative URL without a base }', ', /path/.cargo/registry/src/github.com-1ecc6299db9ec823/mysql-16.0.2/src/conn/opts.rs:827:25

**Comment by blackbeam** [comment]
Hi!

Please handle error using `Opts::from_url`, then pass the result to the `OptsBuilder::from_opts`.

**Comment by nbari** [comment]
Thanks, I came up with this:

```rs
let opts = mysql::Opts::from_url(dsn).unwrap_or_else(|e| {
    eprintln!("verify the DSN: {}", e);
    process::exit(1);
});
let mut opts = mysql::OptsBuilder::from_opts(opts);
opts.stmt_cache_size(0);
let pool = mysql::Pool::new_manual(1, 2, opts).expect("Could not connect to MySQL");
```
