### ISSUE TITLE
 query within `for` gets idle 

### ISSUE THREAD

**Issue by nbari** [blackbeam/rust-mysql-simple#179]
After fetching some values, I would like to do other queries, for example:

```rs
fn enforce_quota(&self) -> Result<(), Error> {
        let rows = self
            .pool
            .prep_exec("SELECT name FROM quotas WHERE bytes > quota", ())?;
        for row in rows {
            let row = row.map_err(Error::MySQL)?;
            let dbname = mysql::from_row_opt::<String>(row)?;
            // this one works
            let users = self
                .pool
                .prep_exec("SELECT user FROM mysql.db WHERE Db=?", (&dbname,))?;
            for user in users {
                let user = user.map_err(Error::MySQL)?;
                let user = mysql::from_row_opt::<String>(user)?;
               // println!("user: {}", user)
               // this one gets stuck, idle
                self.pool.prep_exec(
                    "REVOKE INSERT, UPDATE ON :a.* FROM ':b'@'%'",
                    params! {"a"=>&dbname, "b"=>user},
                )?;
            }
        }
        Ok(())
    }
```

for an unknown reason, the code gets stuck, idle in the query within the second`for`:

```rs
               // println!("user: {}", user) work
                self.pool.prep_exec(
                    "REVOKE INSERT, UPDATE ON :a.* FROM ':b'@'%'",
                    params! {"a"=>&dbname, "b"=>user},
                )?;
```

Any ideas about how to deal with this?

**Comment by nbari** [comment]
I increased the pool size to 3 and manage to make it work:

```rs
let pool = mysql::Pool::new_manual(1, 3, opts).unwrap_or_else(|e| {
        eprintln!("Could not connect: {}", e);
        process::exit(1);
    });
```

If I am right I need a connection per nested loops in this case 3, since won't close the existing one until it finishes If I am correct.


Also, wondering how to pass params like dbname, etc to build more complex queries, currently in my example, I am getting: 

    You have an error in your SQL syntax...  '?.* FROM ':b'@'%'' at line 1 


I was hoping that by using   ` params! {"a"=>&dbname, "b"=>user},` the query could be form like:

    REVOKE INSERT, UPDATE ON dbname.* FROM 'user'@'%'

Could you please give me a hint about how could I improve my code to better utilize the connection pools and in the usage of `params!`?

**Comment by blackbeam** [comment]
Hi.

> If I am right I need a connection per nested loops in this case 3, since won't close the existing one until it finishes If I am correct.

`QueryResult` is lazy and will hold the connection until no data left in the wire. Your options are:
* increase maximum pool bound to maximum number of simultaneously existing `QueryResult` in a single thread of your application (assuming no synchronization between threads during `QueryResult` consumption);
* immediately consume each result into `Vec<_>` (php-like behavior).

> I was hoping that by using params! {"a"=>&dbname, "b"=>user}, the query could be form like:

`params!` functionality is based on the MySql prepared statements and this feature won't allow you to create a placeholder for anything except single column value. 

What you need is the kind of query builder for MySql but this is out of scope for the driver. I once built my own task-specific query builder. It wasn't that hard).

**Comment by nbari** [comment]
Thanks, for now, I am using `format!`, something like this:

```rs
    pool.prep_exec(
                 format!(
                 "REVOKE INSERT, UPDATE, CREATE, ALTER ON `{}`.* FROM '{}'@'{}'"
                 &dbname, user, host
       ),())?;
```
