### ISSUE TITLE
opts.db_get_db_name() returns "" instead of None

### ISSUE THREAD

**Issue by nbari** [blackbeam/rust-mysql-simple#182]
I would like to check if DB is set and if not define one and create the database if not existing, for example:
   
    let dsn = mysql::Opts::from_url(matches.value_of("DSN").unwrap()).unwrap();
    let hast_name = dsn.getname().is_some()
    let mut opts = mysql::OptsBuilder::from_opts(dsn);
    if !has_name {
       opts.db_name(Some("test"));
    }

But if using a DSN not defining the database name:

    let dsn = mysql::Opts::from_url("mysql://foo:bar@localhost") 

When using:

    let has_name = dsn.get_name()

It returns `Some("")` instead of `None `

**Comment by nbari** [comment]
Is there a way to append/add the database name to the pool after it has been created?
  
I was thinking about creating the pool with no database in the `opts`:
 
      let pool = mysql::Pool::new_manual(1, 10, opts);

Check if the database exists and if not create, and then add the database name to the pool but wondering if this is possible or there is a better way to deal with this.

**Comment by blackbeam** [comment]
Hi.

> Is there a way to append/add the database name to the pool after it has been created?

No. It's unclear how to deal with already opened connections. I'd suggest you to probe database existence and create one if needed using `Conn::new`.

> It returns `Some("")` instead of `None`

Thanks. I'll fix it.
