### ISSUE TITLE
how to connect without creating a pool

### ISSUE THREAD

**Issue by nbari** [blackbeam/rust-mysql-simple#183]
How could I connect to the DB not creating a pool, or in any case how after finishing doing the queries, could the pool be closed in order to prevent having the connection sleeping?

I found that I could use `drop(pool)` but how to make it work within a `loop`, for example:

```rs
loop {
   let p = pool.clone();
   // some queries
   drop(p)
   thread::sleep(time::Duration::from_sec(10))
}
```

In this case, it will close until the sleep finishes, not before, thanks in advance.

**Comment by blackbeam** [comment]
Hi.

> How could I connect to the DB not creating a pool

You can do it using [`Conn::new`](https://docs.rs/mysql/16.0.2/mysql/struct.Conn.html#method.new).

> how after finishing doing the queries, could the pool be closed in order to prevent having the connection sleeping?

Pool is ref-counted (`Arc`-based). It'll be closed as soon as there is no references to the pool.

**Comment by tomocrafter** [comment]
Thank for awesome crate!
But Is there any plan to make pool to be feature of crate and users be able to choose with/without pool?
