### ISSUE TITLE
Can't create database with parameter

### ISSUE THREAD

**Issue by bausano** [blackbeam/rust-mysql-simple#188]
I am trying to create a database with the db name as a parameter. With my current setup, I get following error:
```
Error code: 1064
State: 42000
Message: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '?' at line 1.
```
For all of these statements:
```
pool.prepare("CREATE DATABASE ?").unwrap();

pool.prep_exec("CREATE DATABASE ?", (database.name,)).unwrap();

pool.prep_exec("CREATE DATABASE :db", params!{"db" => database.name}).unwrap();
```
While following statement succeed and creates a database:
```
pool.prep_exec("CREATE DATABASE testing-database").unwrap();
```

I am using `mysql = "16"`.

**Comment by blackbeam** [comment]
Hi!

`CREATE DATABASE` statement can be prepared however:

> In general, parameters are legal only in Data Manipulation Language (DML) statements, and not
> in Data Definition Language (DDL) statements.

This means that parameters (i.e. `?`) can't be used in DDL statements.

**Comment by bausano** [comment]
Thank you for your quick response! How would you suggest I prepare the statement?

**Comment by blackbeam** [comment]
In case of the `CREATE DATABASE` statement the only way for you, and for any other mysql user, actually, is to generate query yourself, and then to execute it in a preferred way:

```rust
let query = format!("CREATE DATABASE {}", database.name);
pool.prep_exec(query)?;
```

Note, however that this code assuming that the `database.name` value is trusted.
