### ISSUE TITLE
How to handle and error from executes insert data?

### ISSUE THREAD

**Issue by rchatsiri** [blackbeam/rust-mysql-simple#196]
I'm insert data into ```stmt.execute() ``` as example below, but database found an error from duplicate primary key and send an error back to execute function. How to handle an error from ``` match ``` keyword.
```
let result =stmt.execute(params! { 
    "user_id" => user_ac.user_id,
    "pub_key_temp" => user_ac.pub_key_temp,
    }).unwarp();
 match result {
   .... How to define handler exception from here(mysql::QueryResult<'s>)?... 
 }
```

**Comment by blackbeam** [comment]
Hi!

The [`MySqlError`](https://docs.rs/mysql/17.0.0/mysql/error/struct.MySqlError.html) type exposes `state`, `message` and `code` fields:

```rust
match stmt.execute(params! { /* ... */ }) {
    Ok(_) => (/* inserted */),
    Err(my::Error::MySqlError(err)) => (/* your handler logic here */),
}
```

I would suggest, however, to consider other approaches. See [here](https://chartio.com/resources/tutorials/how-to-insert-if-row-does-not-exist-upsert-in-mysql/) for example.
