### ISSUE TITLE
Temporary table does not exist

### ISSUE THREAD

**Issue by lmatz** [blackbeam/rust-mysql-simple#198]
Hi! I ran the example on the https://docs.rs/mysql/17.0.0/mysql/. The temporary table can be created, and values can be inserted. However, the 'select' query will pop the error `MySqlError { ERROR 1146 (42S02): Table 'mysql.payment' doesn't exist }', src/libcore/result.rs:1189:5`. 

If I change the `Temporary table` to just `table`, everything works fine. I am not sure whether this has to do with the connection pool? The `Temporary table` has to live in a session and all the execution with the table has to go through a single connection?

**Comment by blackbeam** [comment]
Hi.

Yeah, i believe this is due to the fact, that temporary table is only available and accessible to the connection that creates it. Looks like this particular doc-test depends highly on the pool behaviour.

**Comment by lmatz** [comment]
I guess the right way to do here is to acquire a connection first and issue all the queries. Thx!

**Comment by blackbeam** [comment]
Yeah. I'll rewrite it.

**Comment by blackbeam** [comment]
Should be fixed in [v18.0.0](https://github.com/blackbeam/rust-mysql-simple/releases/tag/v18.0.0).
