### ISSUE TITLE
Impossible to prepare multiple statements at once

### ISSUE THREAD

**Issue by weiznich** [blackbeam/rust-mysql-simple#199]
I expect the following code to work
```rust
fn prepare_statements(conn: &mut mysql::Conn) -> (mysql::Stmt, mysql::Stmt) {
    let a = conn.prepare("foo").unwrap();
    let b = conn.prepare("bar").unwrap();
    
    (a, b)
}
```

but this leads to the following error message:

```
error[E0499]: cannot borrow `*conn` as mutable more than once at a time
  --> src/main.rs:16:13
   |
14 | fn prepare_statements(conn: &mut mysql::Conn) -> (mysql::Stmt, mysql::Stmt) {
   |                             - let's call the lifetime of this reference `'1`
15 |     let a = conn.prepare("SELECT id, name FROM users").unwrap();
   |             ---- first mutable borrow occurs here
16 |     let b = conn.prepare("SELECT id, name FROM posts").unwrap();
   |             ^^^^ second mutable borrow occurs here
17 | 
18 |     (a, b)
   |     ------ returning this value requires that `*conn` is borrowed for `'1`
```

(Yes I'm aware of the statement caching in `Conn::prep_exec`, but this requires to have a SQL query string. This implies that one need to actual build that string in a dynamic environment, but sometimes the mapping from parameters to statement could be done without building the query. In such cases it would be helpful to have a way that would allow to build our own statement cache on top of this crate)

**Comment by blackbeam** [comment]
Fix published in [v18.0.0](https://github.com/blackbeam/rust-mysql-simple/releases/tag/v18.0.0).

**Comment by payallmoney** [comment]
" second mutable borrow occurs here " happens again with 
conn.exec_drop after 
conn.query_iter
mysql version is 20.1.0

**Comment by payallmoney** [comment]
> Fix published in [v18.0.0](https://github.com/blackbeam/rust-mysql-simple/releases/tag/v18.0.0).

" second mutable borrow occurs here " happens again with
conn.exec_drop after
conn.query_iter
mysql version is 20.1.0

**Comment by blackbeam** [comment]
@payallmoney, hi.

Could you please share the code sample?

**Comment by payallmoney** [comment]
code is like this : 
use mysql::prelude::*;
use mysql::*;
fn main() -> std::result::Result<(), Box<dyn std::error::Error>> {
    let url = "mysql://root:@127.0.0.1/abc";
    let pool = Pool::new(url).expect("Pool::new error");
    let mut conn = pool.get_conn().expect("get_conn error");
    conn.query_iter("select 1 ")?;
    conn.exec_drop(" insert into ttt ( name ) values('111') ");
}

**Comment by payallmoney** [comment]
> @payallmoney, hi.
> 
> Could you please share the code sample?

use mysql::prelude::*;
use mysql::*;
fn main() -> std::result::Result<(), Box<dyn std::error::Error>> {
    let url = "mysql://root:@127.0.0.1/stock1";
    let pool = Pool::new(url).expect("Pool::new error");
    let mut conn = pool.get_conn().expect("get_conn error");
    let mut result = conn.query_iter("select 1 ")?;
    while let Some(result_set) = result.next_set() {
        let result_set = result_set?;
        for row in result_set {
            let row = row?;
            let code: i32 = row.get(0).unwrap();
            println!("{}", code)
        }
    }
    let mut result1 = conn.query_iter("select 1 ")?;
    while let Some(result_set) = result.next_set() {
        let result_set = result_set?;
        for row in result_set {
            let row = row?;
            let code: i32 = row.get(0).unwrap();
            println!("{}", code)
        }
    }
    Ok(())
}

**Comment by blackbeam** [comment]
The `result` borrows `conn` and it's still in scope when second `query_iter` is called. You need to drop it:

```rust
let pool = crate::Pool::new(get_opts()).expect("Pool::new error");
let mut conn = pool.get_conn().expect("get_conn error");
let mut result = conn.query_iter("select 1 ").unwrap();
while let Some(result_set) = result.next_set() {
    let result_set = result_set.unwrap();
    for row in result_set {
        let row = row.unwrap();
        let code: i32 = row.get(0).unwrap();
        println!("{}", code)
    }
}
drop(result);
let mut result1 = conn.query_iter("select 1 ").unwrap();
while let Some(result_set1) = result1.next_set() {
    let result_set1 = result_set1.unwrap();
    for row in result_set1 {
        let row = row.unwrap();
        let code: i32 = row.get(0).unwrap();
        println!("{}", code)
    }
}
```

**Comment by payallmoney** [comment]
> ```rust
> drop(result);
> ```
Yes , this works pefect 
Thanks for your reply ,   help me a lot  .
