### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by ashishmainali** [blackbeam/rust-mysql-simple#203]
Hey guys, I am new to Rust. I don't know if this is the right place to post but I need to connect to the MySQL database. Where can I find a tutorial to use this library to connect to the database?

**Comment by blackbeam** [comment]
Hi.
First of all you should look into the general example, shipped with the [create docs](https://docs.rs/mysql).

Secondly. It isn't published yet, but the next version [will have some docs](https://github.com/blackbeam/rust-mysql-simple/blob/thin-statement/src/lib.rs) (you should look at the first four hundred lines in that file).
*Note* that the new version will come with breaking API changes, however some topics are still relevant (including `Opts`, connection url, `OptsBuilder`, `Value`, `Row`, `FromValue`, `FromRow`, and some others).

**Comment by blackbeam** [comment]
Please see [crate level docs](https://docs.rs/mysql) for [v18.0.0](https://github.com/blackbeam/rust-mysql-simple/releases/tag/v18.0.0).
