### ISSUE TITLE
Synchronize mysql_common with mysql_async

### ISSUE THREAD

**Issue by AxFaure** [blackbeam/rust-mysql-simple#204]
Hi !

I have been implementing a library using this crate (thank you for sharing it with us by the way) and I created several pieces of software depending on it. My last project is based on an async loop and I would like to reuse my library in this context in a non-blocking fashion. 

I am still unsure what trick I will use to get to that result without having to duplicate too much code.
But it would be extremely convenient to have rust-mysql-simple and mysql_async rely on the same version of mysql_common. (I could downgrade mysql_async but it would mean ditching async/await support).

Do you think you could consider publishing a new version of this crate to have them both use the same version of mysql_common?

**Comment by jonhoo** [comment]
That would also be great to eliminate the dependency on `bytes 0.4` that `mysql_common 0.19` has :)

**Comment by jonhoo** [comment]
Oh, and while we're at it, we could also bump the `nix` dependency to `0.17` :p

**Comment by blackbeam** [comment]
Versions bumped in [v18.0.0](https://github.com/blackbeam/rust-mysql-simple/releases/tag/v18.0.0).
