### ISSUE TITLE
Azure Enforce SSL connection

### ISSUE THREAD

**Issue by 4parsleythelion** [blackbeam/rust-mysql-simple#206]
I know I'm being stupid with this question, but, I'm at a roadblock. I'm using MySQL on Azure, and I can build the connection string using OptsBuilder, and if I switch "off enforce SSL" from the Portal in Azure I can connect and read information from the database.

But, and this is the stupid part, I just can't get the MySQL client to set the link using SSL? Any ideas?

Thank you,

Ashley

**Comment by blackbeam** [comment]
Hi.

Well, i can say, that SSL is supported (see [here](https://docs.rs/mysql/17.0.0/mysql/struct.OptsBuilder.html#method.ssl_opts) and [here](https://docs.rs/mysql/17.0.0/mysql/struct.SslOpts.html)) and that the support itself is [tested](https://travis-ci.org/blackbeam/rust-mysql-simple/jobs/653778006#L967). However there is no way to setup ssl using connection string, you should use [`OptsBuilder::ssl_opts`](https://docs.rs/mysql/17.0.0/mysql/struct.OptsBuilder.html#method.ssl_opts) for this.

Could you please share more details, e.g. debug-print of your `OptsBuilder`? (⚠️ do not forget to cover sensitive data ⚠️)

**Comment by 4parsleythelion** [comment]
First of all, thank you for your kind response to my question. As requested, please find my OptsBuilder below:

Let mut opts = mysql::OptsBuilder::new();
otps.ip_or_hostname(Some(“myDatabase.mysql.database.azure.com”))
        .tcp_port(3306)
        .db_name(Some(“myDatabase”))
        .user(Some(“itsmelook”))
        .pass(Some(“somestrongpassword”))

Let pool = mysql::Pool::new(opts).unwrap();

But I can’t figure out how to add the option that will allow the client to negotiate the SSL with the server, thus allowing me to enable the “enforce SSL” on my Azure database portal.

Thank you for your time and effort to answer my question,

Ashley

**Comment by blackbeam** [comment]
Looks like it's impossible to create Azure subscription from Russia ATM 😔

Have you tried to enable SSL using the default `SslOpts`?

```rust
let mut opts = mysql::OptsBuilder::new();
otps.ip_or_hostname(Some(“myDatabase.mysql.database.azure.com”))
        .tcp_port(3306)
        .db_name(Some(“myDatabase”))
        .user(Some(“itsmelook”))
        .pass(Some(“somestrongpassword”))
        .ssl_opts(mysql::SslOpts::default());  // <- enable SSL with default options

let pool = mysql::Pool::new(opts).unwrap();
```

**Comment by 4parsleythelion** [comment]
Perfect!

Thank you, thank you.

The addition of the: . ssl_opts(mysql::SslOpts::default)) allows me to select the enforce SSL in the Azure portal.

Take care,

Ashley
