### ISSUE TITLE
Support of MariaDb?

### ISSUE THREAD

**Issue by GildedHonour** [blackbeam/rust-mysql-simple#209]
Does it support MariaDb?

**Comment by blackbeam** [comment]
Yeah. Do you have any problems with this?

**Comment by GildedHonour** [comment]
Nope.
Does it support it completely? or with some limitations?

**Comment by blackbeam** [comment]
> Does it support it completely? or with some limitations?

The answer is "no" simply because of [this issue][1].

Is there any particular feature that you're interested in?

[1]: https://github.com/blackbeam/rust-mysql-simple/issues/156

**Comment by GildedHonour** [comment]
No!
