### ISSUE TITLE
Wrong error for: xxx.xxx.xxx.xxx is not allowed to connect to this MySQL server

### ISSUE THREAD

**Issue by frederikbosch** [blackbeam/rust-mysql-simple#21]
When connecting to a server when there is the connection is not allowed, the library comes up with a `DriverError::CouldNotParseVersion`.

The variable [`ver_str`](https://github.com/blackbeam/rust-mysql-simple/blob/master/src/packet.rs#L111) contains the error message `"j\u{4}Host \'192.168.15.250\' is not allowed to connect to this MySQL server`. Adding a simple ```println!("{:?}", &ver_str);``` proved that.

So I guess there should be another error detection in an earlier stage.

**Comment by blackbeam** [comment]
Thanks!

**Comment by frederikbosch** [comment]
Thank you, for your immediate response, and the work!
