### ISSUE TITLE
How to supply a vector of values for IN clause.

### ISSUE THREAD

**Issue by jadedevin13** [blackbeam/rust-mysql-simple#212]
How can you send a Vector of parameter values for an sql like `select * from table_name` in ?`.

When I try, it produces an error.

```rust
^^^^^^^^^^^^ the trait `std::convert::From<std::vec::Vec<std::string::String>>` is not implemented for `mysql::Value`
```

**Comment by blackbeam** [comment]
Hi. Let me cite the [docs]:

> MySql uses ? symbol as a parameter placeholder and it's only possible to use parameters where a single MySql value is expected.

Details:

In accordance to MySql binary protocol, you can supply MySql binary value in place of `?` but _'sequence of MySql binary values'_ is not a MySql binary value.

This question had arisen earlier (see #153).

[docs]: https://docs.rs/mysql/18.0.0/mysql/#binary-protocol-and-prepared-statements
