### ISSUE TITLE
OptsBuilder - self by value 

### ISSUE THREAD

**Issue by nbari** [blackbeam/rust-mysql-simple#213]
Hi, in version `17` I was available to do something like:

```
    let mut opts = mysql::OptsBuilder::new();
    opts.user(dsn.username);
    opts.pass(dsn.password.clone());
    opts.ip_or_hostname(dsn.host);
    if let Some(port) = dsn.port {
        opts.tcp_port(port);
    }
    opts.socket(dsn.socket);
    opts.db_name(dsn.database);
```

Now in version `18` by trying the same way,  I am getting a `use of moved value`, therefore wondering if I have to evaluate the options before adding them what could be the best way of doing it?

I am currently trying something like this but would like to know if there is a better way:

```rs
    let mut opts = mysql::OptsBuilder::new()
        .user(dsn.username)
        .pass(dsn.password.clone())
        .ip_or_hostname(dsn.host)
        .socket(dsn.socket)
        .db_name(dsn.database);
    if let Some(port) = dsn.port {
        opts = opts.tcp_port(port);
    }

    // mysql ssl options
    let mut ssl_opts = mysql::SslOpts::default();
    if let Some(tls) = dsn.params.get("tls") {
        if *tls == "skip-verify" {
            ssl_opts = ssl_opts.with_danger_accept_invalid_certs(true);
        }
    }
    opts = opts.ssl_opts(ssl_opts);
```

Also if possible could you please elaborate more about this change, like what are the benefits, etc, currently I am studying about Rust and would like to learn more about it.

Thanks in advance.

**Comment by blackbeam** [comment]
> Now in version 18 by trying the same way, I am getting a use `of moved value`.

Yeah, `OptsBuilder` is "by value" since v18.

> I am currently trying something like this but would like to know if there is a better way.

It is the best way as far as I know.

> Also if possible could you please elaborate more about this change.

As practice showed, by-ref builder often leads to confusion. See #173 (especially [this comment][1]). The fun thing is that I'm also was struck by this issue once.

[1]: https://github.com/blackbeam/rust-mysql-simple/issues/173#issuecomment-492953159
