### ISSUE TITLE
breaking changes in version 18 (prep_exec) examples

### ISSUE THREAD

**Issue by nbari** [blackbeam/rust-mysql-simple#214]
Hi, I have some code using `prep_exec` for example:

```
let row = self
            .pool
            .prep_exec(
                "SELECT IF(quota > used, true, false) FROM ratelimit WHERE username=?",
                (&username,),
            )?
            .last()
            .ok_or("expecting a row")??;
        Ok(mysql::from_row_opt::<bool>(row)?)
```

But now in version `18` how could I run the same queries now that there is no `prep_exec`, could you please provide some examples.

Thanks in advance.

**Comment by blackbeam** [comment]
Hi.

1.  You can use one of `Queryable::exec*` methods (see [here][1]):

    ```rust
    use mysql::prelude::*;

    let val: book = pool
        .get_conn()?
        .exec_first(
            "SELECT IF(quota > used, true, false) FROM ratelimit WHERE username=?",
            (&username,),
        )?
        .ok_or("expecting a row")?;

    Ok(val)
    ````

2.  You can use `BinQuery` trait (see [here][2]):

    ```rust
    use mysql::prelude::*;

    let val: bool = "SELECT IF(quota > used, true, false) FROM ratelimit WHERE username=?"
        .with((&username,))
        .exec_first(&pool)?
        .ok_or("expecting a row")?;

    Ok(val)
    ```

[1]: https://docs.rs/mysql/18.0.0/mysql/index.html#queryable
[2]: https://docs.rs/mysql/18.0.0/mysql/index.html#binquery-and-batchquery-traits

**Comment by nbari** [comment]
Hi @blackbeam many thanks, regarding the use of `exec_first` If the query returns no records how to identify or return something like empty strings instead of an error.

For example, I found that I could do something like:
    
```
let row = conn.exec_first::<(String, String), _, _>(
     "SELECT name, email FROM users WHERE name=? OR email=?",
     (&username, &email),
)?;
```

So `conn.exec_first::<(String, String), _, _>` includes the `Fromrow`, but the others, `S: AsStatement` and `P: Into` how to use them?

In the examples above I use `.ok_or("expecting a row")?;` but how instead would be the best way to probably return an Option so that if no records are present a `None` could be used instead of throwing an error?

**Comment by blackbeam** [comment]
> regarding the use of `exec_first` If the query returns no records how to identify or return something like empty strings instead of an error

You meant this?:

```rust
let row: (String, String) = conn
    .exec_first(
        "SELECT name, email FROM users WHERE name=? OR email=?",
        (&username, &email),
    )?
    .unwrap_or_default(); // row will be `(String::default(), String::default())` in case of no rows in query result
```

> In the examples above I use .ok_or("expecting a row")?; but how instead would be the best way to probably return an Option so that if no records are present a None could be used instead of throwing an error?

You meant this?:

```rust
let row: Option<(String, String)> = conn
    .exec_first(
        "SELECT name, email FROM users WHERE name=? OR email=?",
        (&username, &email),
    )?;
```

**Comment by nbari** [comment]
Hi @blackbeam thanks that worked 👍

**Comment by dten** [comment]
the docs still mention prep_exec by the way
