### ISSUE TITLE
How do you add alias to a column?

### ISSUE THREAD

**Issue by jadedevin13** [blackbeam/rust-mysql-simple#216]
I'm doing something like

```rust
        .prep_exec("SELECT :select FROM something", params! {"select" => "something.id AS something__id"})
```

But the `row.get("something__id")` keeps on returning None.

**Comment by blackbeam** [comment]
Hi.

[Named parameters][1] are implemented on the client side and actually backed by MySql prepared statements. So server will see your statement as `SELECT ? FROM something`, and will execute it as `SELECT 'something.id AS something__id' FROM something`. This means that it will return single row that will contain single unnamed column with value `something.id AS something__id`.

Note also, that `?` placeholder in the MySql prepared statement will work only for a single MySql value. It won't work for column names, chunks of SQL, multiple MySql values or anything like that (see [here][2]).

[1]: https://docs.rs/mysql/18.1.0/mysql/#named-parameters
[2]: https://dev.mysql.com/doc/refman/8.0/en/sql-prepared-statements.html

**Comment by blackbeam** [comment]
Oh! I forgot about the actual question 😅

> How do you add alias to a column?

You can add alias to a column using the corresponding SQL syntax (already known to you, as far as i can see):

```sql
SELECT something.id AS something__id FROM something
```

If you want to build your query at runtime, then you should use a query builder (this feature is out of scope for this database driver).

**Comment by jadedevin13** [comment]
Thank you. I thought I can use the parameters for any part of the query.
