### ISSUE TITLE
error: linking with `gcc` failed: exit code: 1

### ISSUE THREAD

**Issue by juaby** [blackbeam/rust-mysql-simple#217]
error: linking with `gcc` failed: exit code: 1
  |
  = note: "gcc" "-fno-use-linker-plugin" "-Wl,--nxcompat" "-nostdlib" "-m64"
  = note: *\target\debug\deps\libbacktrace_sys-31ba6dea43c3d34c.rlib(alloc.o):alloc.c:(.text$__rbt_backtrace_alloc+0x37): undefined reference to `__errno'
          *\target\debug\deps\libbacktrace_sys-31ba6dea43c3d34c.rlib(alloc.o):alloc.c:(.text$__rbt_backtrace_vector_grow+0xbf): undefined reference to `__errno'
          *\target\debug\deps\libbacktrace_sys-31ba6dea43c3d34c.rlib(alloc.o):alloc.c:(.text$__rbt_backtrace_vector_release+0x80): undefined reference to `__errno'
          *\target\debug\deps\libbacktrace_sys-31ba6dea43c3d34c.rlib(posix.o):posix.c:(.text$__rbt_backtrace_open+0x48): undefined reference to `__errno'
          *\target\debug\deps\libbacktrace_sys-31ba6dea43c3d34c.rlib(posix.o):posix.c:(.text$__rbt_backtrace_open+0x60): undefined reference to `__errno'
          *\target\debug\deps\libbacktrace_sys-31ba6dea43c3d34c.rlib(posix.o):posix.c:(.text$__rbt_backtrace_close+0x20): more undefined references to `__errno' follow

**Comment by juaby** [comment]
mysql version 17.0.0 OR 18.1.0

**Comment by blackbeam** [comment]
Hi. I believe the issue is in your environment? Did you try to build something without `mysql` dependency?

**Comment by juaby** [comment]
very strange, without mysql dependency, my program can be compiled through

**Comment by blackbeam** [comment]
I think it's because `libbacktrace-sys` is in your dependency tree because of mysql`. I'll try to recreate your environment.

Btw, did you tried rust msvc?

**Comment by juaby** [comment]
[backtrace-rs issues](https://github.com/rust-lang/backtrace-rs/issues/190)

**Comment by juaby** [comment]
> I think it's because `libbacktrace-sys` is in your dependency tree because of `mysql`. I'll try to recreate your environment.
> 
> Btw, did you tried rust msvc?

i will try

**Comment by juaby** [comment]
Hi, here: 
.rustup\toolchains\stable-x86_64-pc-windows-gnu\lib\rustlib\x86_64-pc-windows-gnu\bin>gcc.exe -v
Using built-in specs.
COLLECT_GCC=gcc.exe
Target: x86_64-w64-mingw32
Configured with: '*'
Thread model: posix
gcc version 6.3.0 (x86_64-posix-seh-rev2, Built by MinGW-W64 project)

so issue is my environment. 
```test
OS : win10
Cygwin64: 3.1.4 => GCC: 9.3.0
Rust : 1.42
```
rust's x86_64-pc-windows-gnu rust needs to match GCC version 6.3.0.

I have switched Cygwin64 to MinGW-W64 project ...... DONE
