### ISSUE TITLE
Unable to fetch more than arity 12 using Trait mysql::prelude::FromRow

### ISSUE THREAD

**Issue by bsodmike** [blackbeam/rust-mysql-simple#223]
"Trait to convert Row into a tuple of FromValue implementors up to arity 12."

What's the work around to fetch much larger number of fields? (I'm looking to fetch around 60 fields on a single row, basically the results of `SHOW SLAVE STATUS`).

Thanks!

**Comment by blackbeam** [comment]
Hi.

Please use [`Row`][1] for this. It can be indexed by a column name (e.g. `row["column_name"]`) or by a column index (e.g `row[0]`). Also cell values can be taken using `Row::take`.

Example:

```rust
let query = "SELECT customer_id, amount, account_name from payment";
let selected_payments = conn
    .query_map(
        query,
        |row: mysql::Row| {
            Payment {
                customer_id: row[0],
                amount: row[1],
                account_name: row.take(2).expect("unreachable"),
            }
        },
    )?;
```

[1]: https://docs.rs/mysql/18.2.0/mysql/struct.Row.html

**Comment by bsodmike** [comment]
Thanks @blackbeam.  I'd suggest adding the example above showing how to access row elements with `row: mysql::Row` into the README, that would be super helpful.  I was fetching a large table and got stuck with `FromRow`'s limitation.
