### ISSUE TITLE
Misleading error message on wrong login

### ISSUE THREAD

**Issue by dylan-bowker** [blackbeam/rust-mysql-simple#224]
I received the following panic:

thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: DriverError { Unknown authentication protocol: `sha256_password` }'

For an incorrect user/password combination. I had a bit of a panic myself, that I somehow broke something that would be hard to fix, but it turned out that I had accidentally changed the user name.

**Comment by blackbeam** [comment]
Hi.

An actual "wrong login" error will look similar to this:

```
Access denied for user 'wrong_login'@'localhost' (using password: YES)
```

It seems that in your case the login isn't actually wrong, but belongs to a user with the `sha256_password` plugin in its settings.

**Comment by antcoder** [comment]
`mysql://root:1q2w3e!Q@W#@localhost:3306/database`
![image](https://user-images.githubusercontent.com/1251765/83009263-0e3a9b00-a049-11ea-88a6-fa9d16094b80.png)
hostname err, because '@'?

**Comment by blackbeam** [comment]
@antcoder, yeah. According to URL requirements, password must be properly URL-encoded.

**Comment by blackbeam** [comment]
Closed due to inactivity. Feel free to reopen.
