### ISSUE TITLE
Connecting to RDS with a *.pem certificate

### ISSUE THREAD

**Issue by biot023** [blackbeam/rust-mysql-simple#225]
Hi -- I've updated to the latest version of the crate but now have the issue that I need to connect with TLS using a *.pem certificate and the current version doesn't seem to support this.
I followed the instructions in the docs as best I could but I'm getting a `TlsHandshakeError`, probably because I don't have the private key -- I'll know better when I research this more.
I've seen a related issue ticket linked to a broken pull request that I will look into and I will research that and speak to AWS support about other ways to connect to the RDS, generally.
If there's any insight or recommendations anybody here could offer in the meantime, though, that would be really helpful, even if it's things to look into that might help me fix this issue with a hack. I'll either need to roll back the code to using v 0.16 or two key projects are effectively stalled.
Thanks for any and all advice,
   Doug.

**Comment by blackbeam** [comment]
Hi.

*   Am I right that your `pem` certificate is an amazon root certificate taken from [here][1]?
*   Could you please tell me what you have tried already?
    *   Have you tried to convert your `pem` to `der` and feed it into [`SslOpts::with_root_cert_path`][2]?
    *   Have you tried to [create a keyless pkcs12 container][3] and feed it into [`SslOpts::with_pkcs12_path`][4]?
*   Could you please share the full text of an actual error?

[1]: https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/UsingWithRDS.SSL.html
[2]: https://docs.rs/mysql/18.2.0/mysql/struct.SslOpts.html#method.with_root_cert_path
[3]: https://stackoverflow.com/a/23941513
[4]: https://docs.rs/mysql/18.2.0/mysql/struct.SslOpts.html#method.with_pkcs12_path

**Comment by blackbeam** [comment]
I've made the following from my Linux server:

1. Created a free RDS instance (mysql 5.7)
2. Downloaded `rds-ca-2019-root.pem` from [this page][1]
3. Converted pem to der using the following command:

    ```
    $ openssl x509 -outform der -in ./rds-ca-2019-root.pem -out ./rds-ca-2019-root.der
    ```

4. Written the following test program:

    ```rust
    fn main() -> Result<()> {
        let cert_path = std::path::Path::new("rds-ca-2019-root.der");
        let ssl_opts = SslOpts::default().with_root_cert_path(Some(cert_path));

        let opts = OptsBuilder::from_opts("mysql://admin:******@test-rds-ssl.cchm2sqw4csw.ap-southeast-1.rds.amazonaws.com")
            .ssl_opts(ssl_opts);
        let mut conn = Conn::new(opts)?;

        let (_, cipher): (Value, String) = "SHOW STATUS LIKE 'Ssl_cipher'".first(&mut conn)?.unwrap();

        println!("Cipher in use: {}", cipher);

        Ok(())
    }
    ```

5. The result was:

    ![изображение](https://user-images.githubusercontent.com/155883/81279024-36913400-905f-11ea-8e49-606ed49e90a6.png)

So I believe everything works as expected.

[1]: https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/UsingWithRDS.SSL.html

**Comment by biot023** [comment]
Hmm. I wonder if maybe it's because the *.pem file I'm using is the bundle?
I'll try with the 2019 specific one and see how that goes -- cheers!

**Comment by biot023** [comment]
Aaaand we have a connection!
Thanks again, man -- I should've thought of that.
