### ISSUE TITLE
Converting hostname to IP address

### ISSUE THREAD

**Issue by Ziris85** [blackbeam/rust-mysql-simple#230]
Hello! Forgive me if this question isn't related to this crate or if there's something obvious that I'm missing as I'm still just dipping my toes into Rust in general. However, I've been tinkering with establishing a connection with MySQL using this crate, but it seems that it fails where it shouldn't be.

I have a file that my code reads that pulls in mysql connection info from, and in there the hostname is set to "localhost". However, when I try to use this, it seems to be converting it to the 127.0.0.1 IP address (which, as you may know, MySQL users are highly dependent on how you connect to the service) and causing the connection to fail, since the user is @'localhost', and not @'127.0.0.1'. Is there a way to stop this from happening? I can provide some example output and code if needed.

Thank you in advance!

**Comment by blackbeam** [comment]
Hi. I believe `@localhost` means socket connection.

There is a way to enforce socket connection using either `socket` connection url parameter (documented [here][1]) or `socket` option (documented [here][2]).

[1]: https://docs.rs/mysql/18.2.0/mysql/#url-based-connection-string
[2]: https://docs.rs/mysql/18.2.0/mysql/struct.OptsBuilder.html#method.socket

**Comment by Ziris85** [comment]
Thank you for the response! I think I'm starting to understand, and it's ending up being a misunderstanding on my end. I was comparing what this was doing to how the mysql client connects, which ended up being an inappropriate comparison. It seems that, if passed "localhost" the mysql client will connect to the socket _first_, whereas this crate will connect to the socket only if the TCP connection succeeds first (which `prefer_socket` doesn't work here since the TCP connection never succeeds with that). So, if I add a conditional to connect to the socket if "localhost" is the hostname, my connection succeeds.

Thanks for your help @blackbeam !
