### ISSUE TITLE
Options from HashMap?

### ISSUE THREAD

**Issue by rjcortese** [blackbeam/rust-mysql-simple#232]
Hello,
Any thoughts on adding something like `Opts::from_hashmap(&myOptsMap)`?
I don't think such a feature exists yet.
I made a crate https://github.com/rjcortese/myloginrs that parses `.mylogin.cnf` and returns a HashMap and I think adding this feature would make it really simple to interface with this crate.
I'd also be interested in adding it to the async version.

**Comment by hpca01** [comment]
@blackbeam I can work on this if you'd like, seems like low hanging fruit and I use something similar in one of projects that I wrote with this lib.

**Comment by blackbeam** [comment]
@hpca01, that would be great.

**Comment by hpca01** [comment]
#256

**Comment by blackbeam** [comment]
Published as [v20.1.0](https://github.com/blackbeam/rust-mysql-simple/releases/tag/v20.1.0)
