### ISSUE TITLE
Get Column Value by name?

### ISSUE THREAD

**Issue by Alexander9673** [blackbeam/rust-mysql-simple#240]
Hello, i was wondering if i could actually get the value from a column. I know that `row["column_name"]` exists, but that returns a `Value`, which then when i use `from_value` on it, i keep getting a `Value does not implement Copy`. Any fixes?

**Comment by blackbeam** [comment]
Hi. Your options are:
*   [`Row::get`][1]
*   [`Row::get_opt`][2]
*   [`Row::take`][3]
*   [`Row::take_opt`][4]

[1]: https://docs.rs/mysql/18.2.0/mysql/struct.Row.html#method.get
[2]: https://docs.rs/mysql/18.2.0/mysql/struct.Row.html#method.get_opt
[3]: https://docs.rs/mysql/18.2.0/mysql/struct.Row.html#method.take
[4]: https://docs.rs/mysql/18.2.0/mysql/struct.Row.html#method.take_opt

**Comment by Alexander9673** [comment]
But aren't those for nums only? Or does the param accept strings

**Comment by blackbeam** [comment]
Yeah. The parameter is defined as `I: ColumnIndex`, and the `ColumnIndex`, [as you can see here][1], is defined for both `usize` and `&'a str`.

[1]: https://docs.rs/mysql/18.2.0/mysql/prelude/trait.ColumnIndex.html#foreign-impls

**Comment by Alexander9673** [comment]
ok thank you, one last question. About the mysql types, why are the some missing ones? https://www.mysqltutorial.org/mysql-data-types.aspx/ this is where im looking, and im comparing it with the `consts` struct/trait, and was wondering why are some missing?

**Comment by blackbeam** [comment]
Which one you think is missing? There are plenty of supported types ([see here][1]).

[1]: https://github.com/blackbeam/rust_mysql_common#supported-rust-types

**Comment by blackbeam** [comment]
Or did I misunderstood you?

**Comment by Alexander9673** [comment]
> Or did I misunderstood you?

Somewhat like that yeah, since `mysql::consts` is what i'm using, i'm trying to find some types that are appropriate to be a string, a int, uint or float

**Comment by blackbeam** [comment]
Oh, the mapping between protocol types and SQL types is documented here: https://dev.mysql.com/doc/refman/8.0/en/c-api-prepared-statement-type-codes.html

I'm not sure on what is your goal exactly, but note that all this is quite low level and might not be what your need.

**Comment by Alexander9673** [comment]
That's what i needed, ty
