### ISSUE TITLE
Update README example to work with the newest version

### ISSUE THREAD

**Issue by Phiwatec** [blackbeam/rust-mysql-simple#258]
I tried to compile the example given in the README using the newest rustc and it won't compile because the get_conn() function is not a part of pool. So could someone with more experience in Rust and this library update the example code , so that it compiles again. :)
For someone trying out the library for the first time,it is really frustating if not even the simple example compiles successfully. 
Greetings

**Comment by blackbeam** [comment]
Hi, @Phiwatec. Thanks for remind me about README.md. It's now updated (see cfb295b), but this, most likely, won't fix your issue because:

1. the `get_conn` function _is_ the part of the Pool structure ([proof][1]);
2. every code snippet in README.md is tested on the latest compiler ([proof][2]).

Could you please share your code and the actual error message?

[1]: https://docs.rs/mysql/20.1.0/mysql/struct.Pool.html#method.get_conn
[2]: https://dev.azure.com/aikorsky/mysql%20Rust/_build/results?buildId=132&view=logs&j=d9a650d5-9a56-5a67-2201-cbd6b5e3b462&t=50c3c2ea-06a7-5cae-3e89-fcea01d048f1&l=262

**Comment by Phiwatec** [comment]
Okay, im using the most current verson of the rustc nightly.
Im just using the example code in a fn main without any modifications. Build system is Debian 10. 
Error is the following:
`dev@dev:~/testdev/mysql$ cargo run
   Compiling mysql v0.1.0 (/home/dev/testdev/mysql)
    Building [=====================================================> ] 144/145: mysql(bin)                                                                                                                   
error[E0599]: no method named `get_conn` found for enum `std::result::Result<mysql::Pool, mysql::Error>` in the current scope
  --> src/main.rs:17:25
   |
17 |     let mut conn = pool.get_conn();
   |                         ^^^^^^^^ method not found in `std::result::Result<mysql::Pool, mysql::Error>`

warning: unused import: `mysql::prelude`
 --> src/main.rs:2:5
  |
2 | use mysql::prelude::*;
  |     ^^^^^^^^^^^^^^
  |
  = note: `#[warn(unused_imports)]` on by default

error: aborting due to previous error; 1 warning emitted

For more information about this error, try `rustc --explain E0599`.
error: could not compile `mysql`

To learn more, run the command again with --verbose.`
I removed the questionmark operators because it to gave me an error:
`dev@dev:~/testdev/mysql$ cargo run
   Compiling mysql v0.1.0 (/home/dev/testdev/mysql)
error[E0277]: the `?` operator can only be used in a function that returns `Result` or `Option` (or another type that implements `Try`)
  --> src/main.rs:15:16
   |
3  | / fn main(){
4  | |     
5  | |
6  | |
...  |
15 | |     let pool = Pool::new(url)?;
   | |                ^^^^^^^^^^^^^^^ cannot use the `?` operator in a function that returns `()`
...  |
59 | |     println!("Yay!");
60 | | }
   | |_- this function should return `Result` or `Option` to accept `?`
   |
   = help: the trait `Try` is not implemented for `()`
   = note: required by `from_error`

error[E0277]: the `?` operator can only be used in a function that returns `Result` or `Option` (or another type that implements `Try`)
  --> src/main.rs:17:20
   |
3  | / fn main(){
4  | |     
5  | |
6  | |
...  |
17 | |     let mut conn = pool.get_conn()?;
   | |                    ^^^^^^^^^^^^^^^^ cannot use the `?` operator in a function that returns `()`
...  |
59 | |     println!("Yay!");
60 | | }
   | |_- this function should return `Result` or `Option` to accept `?`
   |
   = help: the trait `Try` is not implemented for `()`
   = note: required by `from_error`

error[E0277]: the `?` operator can only be used in a function that returns `Result` or `Option` (or another type that implements `Try`)
  --> src/main.rs:20:5
   |
3  |  / fn main(){
4  |  |     
5  |  |
6  |  |
...   |
20 | /|     conn.query_drop(
21 | ||         r"CREATE TEMPORARY TABLE payment (
22 | ||             customer_id int not null,
23 | ||             amount int not null,
24 | ||             account_name text
25 | ||         )")?;
   | ||____________^ cannot use the `?` operator in a function that returns `()`
...   |
59 |  |     println!("Yay!");
60 |  | }
   |  |_- this function should return `Result` or `Option` to accept `?`
   |
   = help: the trait `Try` is not implemented for `()`
   = note: required by `from_error`

error[E0277]: the `?` operator can only be used in a function that returns `Result` or `Option` (or another type that implements `Try`)
  --> src/main.rs:36:5
   |
3  |  / fn main(){
4  |  |     
5  |  |
6  |  |
...   |
36 | /|     conn.exec_batch(
37 | ||         r"INSERT INTO payment (customer_id, amount, account_name)
38 | ||           VALUES (:customer_id, :amount, :account_name)",
39 | ||         payments.iter().map(|p| params! {
...  ||
43 | ||         })
44 | ||     )?;
   | ||______^ cannot use the `?` operator in a function that returns `()`
...   |
59 |  |     println!("Yay!");
60 |  | }
   |  |_- this function should return `Result` or `Option` to accept `?`
   |
   = help: the trait `Try` is not implemented for `()`
   = note: required by `from_error`

error[E0277]: the `?` operator can only be used in a function that returns `Result` or `Option` (or another type that implements `Try`)
  --> src/main.rs:47:29
   |
3  |  / fn main(){
4  |  |     
5  |  |
6  |  |
...   |
47 |  |     let selected_payments = conn
   |  |_____________________________^
48 | ||         .query_map(
49 | ||             "SELECT customer_id, amount, account_name from payment",
50 | ||             |(customer_id, amount, account_name)| {
51 | ||                 Payment { customer_id, amount, account_name }
52 | ||             },
53 | ||         )?;
   | ||__________^ cannot use the `?` operator in a function that returns `()`
...   |
59 |  |     println!("Yay!");
60 |  | }
   |  |_- this function should return `Result` or `Option` to accept `?`
   |
   = help: the trait `Try` is not implemented for `()`
   = note: required by `from_error`

error: aborting due to 5 previous errors

For more information about this error, try `rustc --explain E0277`.
error: could not compile `mysql`

To learn more, run the command again with --verbose.`
Cargo.toml has dependency mysql="20.1.0"
Maybe there's a simple issue I don't see. If this is the case I'm sorry for bothering you. 
Greetings

**Comment by blackbeam** [comment]
Oh, i see. This issue is not related to this crate, so I'm closing it.

Regarding your issue.
As you said, you removed the questionmark operators. This means that all corresponding values are wrapped in [`Result`][1]s. You should either [`unwrap`][2] them, or proply handle all possible errors.

Note, that the precense of the question mark operator in any valid code entails, that this code is located in some valid context (in terms of the question mark operator). In this concrete case – it is located within the following function:

```
fn main() -> std::result::Result<(), Box<dyn std::error::Error>> {
    // ...
}
```

I suggest you to taught yourself through [The rust book][3]. Especially the "Error handling" section.

[1]: https://doc.rust-lang.org/std/result/enum.Result.html
[2]: https://doc.rust-lang.org/std/result/enum.Result.html#method.unwrap
[3]: https://doc.rust-lang.org/book/title-page.html
