### ISSUE TITLE
PooledConnection docs wrongfully suggest “prepare” and “prep_exec”

### ISSUE THREAD

**Issue by Zomtir** [blackbeam/rust-mysql-simple#260]
The latest doc pages for the PooledConnection of the mysql crate still suggest to make use of "prepare" and "prep_exec":

> "You should prefer using prepare or prep_exec instead of query where possible, except cases when statement has no params and when it has no return values or return values which evaluates to Value::Bytes"

This is wrong ever since those functions were deprecated and/or moved to mysql::prelude::Queryable under different names.

Patch in the works.

**Comment by blackbeam** [comment]
@Zomtir, thanks!
