### ISSUE TITLE
LOAD DATA LOCAL INFILE no effect

### ISSUE THREAD

**Issue by AliThink** [blackbeam/rust-mysql-simple#266]
`LOAD DATA LOCAL INFILE '/xx/xx.csv' INTO TABLE table_name fields terminated by ',' IGNORE 1 LINES`
Data can be inserted successful when run this command in mysql console, but no effect when i use the conn.query_drop method to do the same thing as below.
`conn.query_drop( r"LOAD DATA LOCAL INFILE '/xx/xx.csv' INTO TABLE table_name fields terminated by ',' IGNORE 1 LINES")?;`
Nothing to be inserted, the table is still empty.

Does LocalInfileHandler must be configured when using load data local infile to import data to mysql?

**Comment by blackbeam** [comment]
Hi.
Looks like [the docs][1] are a bit outdated, namely, the default value for the `local_infile_hanler` [is none][2].
So yeah, you should configure the handler.

[1]: https://docs.rs/mysql/20.1.0/mysql/struct.OptsBuilder.html#method.local_infile_handler
[2]: https://docs.rs/mysql/20.1.0/src/mysql/conn/opts.rs.html#222

**Comment by AliThink** [comment]
Got it, thanks for your reply.
