### ISSUE TITLE
The Mysql Crate support read the table -> column -> Comment ?

### ISSUE THREAD

**Issue by TQLeung** [blackbeam/rust-mysql-simple#276]
my english is poor, i am so sorry..
The Mysql Crate support read the table -> column -> Comment ? see the code with **Bold**

CREATE TABLE `some_table`  (
  `PK_ID` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL COMMENT '**主键ID**',
  `CREATE_USER` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '**创建人ID**',

Or

Read the table's metadata, like types, comments,

**Comment by blackbeam** [comment]
Hi. Table metadata are stored within the `INFORMATION_SCHEMA`. Here is an example query (adapted from [here][1]):

```sql
SELECT column_comment
FROM information_schema.columns
WHERE table_schema = 'your_db_name' AND table_name = 'your_table_name' AND column_name = 'your_column_name';

```

Closing, since it's not related to the driver.

[1]: https://stackoverflow.com/questions/5097973/access-mysql-fields-comments-with-php/9495922
