### ISSUE TITLE
make some fn pub

### ISSUE THREAD

**Issue by jiuker** [blackbeam/rust-mysql-simple#281]
read_packet
write_command
When I try to Do mysql Replicaion,I need this fn pub,thanks

**Comment by blackbeam** [comment]
Hi. This calls aren't supposed to be public.

Btw, have you seen [this recently released functionality](https://docs.rs/mysql/21.0.0/mysql/struct.Conn.html#method.get_binlog_stream)? You can now register as a slave and subscribe to a binlary log stream (please see [this test][2] as an illustration).

[2]: https://github.com/blackbeam/rust-mysql-simple/blob/master/src/conn/mod.rs#L2056

**Comment by jiuker** [comment]
thx
