### ISSUE TITLE
example code does not work in version 21 mysql crate

### ISSUE THREAD

**Issue by haochiya** [blackbeam/rust-mysql-simple#283]
CODE:
use mysql::*;
use mysql::prelude::*;
fn main() {
let url = "mysql://root:password@localhost:3307/db_name";
let pool = Pool::new(url).unwrap();
let mut conn = pool.get_conn().unwrap();
....
}

ERROR:
let pool = Pool::new(url).unwrap();
                                the trait 'From<&str>' is not implemented for 'Opts'

**Comment by blackbeam** [comment]
Hi.
The `From<&str> for Opts` impl was removed in v21, sorry for not mentioning in the release notes. I'll migrate to `TryFrom` in the future, but for now please use `Opts::from_url`:

```rust
use mysql::*;
use mysql::prelude::*;
fn main() {
let url = "mysql://root:password@localhost:3307/db_name";
let opts = Opts::from_url(url).unwrap();
let pool = Pool::new(opts).unwrap();
let mut conn = pool.get_conn().unwrap();
```

**Comment by haochiya** [comment]
Thank you！
