### ISSUE TITLE
rocket v0.5-rc and rust-mysql-simple

### ISSUE THREAD

**Issue by Njamen** [blackbeam/rust-mysql-simple#287]
Please how the use this library with rocket v0.5-rc

**Comment by blackbeam** [comment]
Hi, sorry for late response.
rocket v0.5 seem to be async, so I suggest you to consider the mysql_async crate instead.

Regarding your question - I'm not really familiar with rocket, but you could look at https://github.com/SergioBenitez/Rocket/tree/master/contrib/db_pools
