### ISSUE TITLE
Latest version will not compile if the latest `lapin` crate is in the project

### ISSUE THREAD

**Issue by biot023** [blackbeam/rust-mysql-simple#289]
If I create a new project:

```bash
cargo new --bin testing-mysql-and-lapin
cd testing-mysql-and-lapin
```

Then add `mysql` and build:

```bash
cargo add mysql
cargo check
```

All is good. Now, if I add `lapin` and build:

```bash
cargo add lapin
cargo check
```

I get a rash of errors that seem to be based around conflicts of the two projects' versions of `bitvec`.
`mysql` uses `bitvec` 0.22.3 and `lapin` appears to use (via `amp-protocol` and `nom`) 0.19.4

Hopefully this is the right place to report this -- let me know if you think I should be whining in the `lapin` project issues. :)

**Comment by blackbeam** [comment]
This seem to be resolved by lapin v1.8.0.
