### ISSUE TITLE
Is it only way to implement FromRow?

### ISSUE THREAD

**Issue by e-oz** [blackbeam/rust-mysql-simple#29]
Hello. I have table with 18 columns, so I have to implement FromRow for my structure.
```rust
pub struct Contact {
	id: u64,
	fname: String,
	lname: String,
	address: String,
	address2: String,
	city: String,
	state: String,
	zip: String,
	email: String,
	phone: String,
	manager_id: u64,
	user_id: u64,
	location_1_id: String,
	location_2_id: String,
	location_3_id: String,
	position: String,
	facility_name: String,
	speciality: String
}

impl FromRow for Contact {
	fn from_row(row: Vec<Value>) -> Contact {
		FromRow::from_row_opt(row)
		.ok().expect("Could not convert row to (T1-T18)")
	}
	fn from_row_opt(mut row: Vec<Value>) -> Result<Contact, Vec<Value>> {
		let vs = (from_value_opt(row.pop().unwrap()),
		from_value_opt(row.pop().unwrap()),
		from_value_opt(row.pop().unwrap()),
		from_value_opt(row.pop().unwrap()),
		from_value_opt(row.pop().unwrap()),
		from_value_opt(row.pop().unwrap()),
		from_value_opt(row.pop().unwrap()),
		from_value_opt(row.pop().unwrap()),
		from_value_opt(row.pop().unwrap()),
		from_value_opt(row.pop().unwrap()),
		from_value_opt(row.pop().unwrap()),
		from_value_opt(row.pop().unwrap()),
		from_value_opt(row.pop().unwrap()),
		from_value_opt(row.pop().unwrap()),
		from_value_opt(row.pop().unwrap()),
		from_value_opt(row.pop().unwrap()),
		from_value_opt(row.pop().unwrap()),
		from_value_opt(row.pop().unwrap())
		);
		match vs {
			(Ok(t18),Ok(t17),Ok(t16),Ok(t15),Ok(t14),Ok(t13),Ok(t12), Ok(t11), Ok(t10), Ok(t9), Ok(t8), Ok(t7), Ok(t6), Ok(t5), Ok(t4), Ok(t3), Ok(t2), Ok(t1)) =>  {
				Ok(Contact{id: t1,
					fname: t2,
					lname: t3,
					address: t4,
					address2: t5,
					city: t6,
					state: t7,
					zip: t8,
					email: t9,
					phone: t10,
					manager_id: t11,
					user_id: t12,
					location_1_id: t13,
					location_2_id: t14,
					location_3_id: t15,
					position: t16,
					facility_name:t17,
					speciality: t18})
			},
			_ => {
				Err(row)
			}
		}
	}
}
```
Is it the only way? With all of these copy-pasted lines and unwraps?

**Comment by blackbeam** [comment]
I do not think there is a way to get rid of it.

But maybe if someone decided to user `HashMap<String, String>` instead of plain struct to make it all more PHPish :smile: 

But seriously `FromRow` was never intended to replace ORM in any way.
I saw a few ORMs at crates.io. But not sure they are in a good shape..

**Comment by e-oz** [comment]
Yeah, HashMap<String,String> would be much more easy. Really, there are tables with hundreds of columns, literally, I saw them and has worked with them. Hundreds of Ok(x) and `from_value_opt(row.pop().unwrap())` don't sound too funny.

**Comment by e-oz** [comment]
But actually there is a way! :)
```rust
		let contact = Contact{
			id: try!(from_value_opt(r.pop().unwrap())),
			fname:try!(from_value_opt(r.pop().unwrap())),
			lname:try!(from_value_opt(r.pop().unwrap())),
			address:try!(from_value_opt(r.pop().unwrap())),
			address2:try!(from_value_opt(r.pop().unwrap())),
			city:try!(from_value_opt(r.pop().unwrap())),
			state:try!(from_value_opt(r.pop().unwrap())),
			zip:try!(from_value_opt(r.pop().unwrap())),
			email:try!(from_value_opt(r.pop().unwrap())),
			phone:try!(from_value_opt(r.pop().unwrap())),
			manager_id:try!(from_value_opt(r.pop().unwrap())),
			user_id:try!(from_value_opt(r.pop().unwrap())),
			location_1_id:try!(from_value_opt(r.pop().unwrap())),
			location_2_id:try!(from_value_opt(r.pop().unwrap())),
			location_3_id:try!(from_value_opt(r.pop().unwrap())),
			position:try!(from_value_opt(r.pop().unwrap())),
			facility_name:try!(from_value_opt(r.pop().unwrap())),
			speciality:try!(from_value_opt(r.pop().unwrap()))
		};
```
count of lines  = count of columns.

Found by @defuz in Ru Rustlang communuty chat: https://gitter.im/ruRust/general?at=56524051541ec57a66e30365

**Comment by e-oz** [comment]
(sorry for spam, previous code was removed because it wasn't actually working, despite of succsessfull compilation)

```rust
		let contact = Contact{
			id: from_value_opt(r[0].clone()).unwrap(),
			fname: from_value_opt(r[1].clone()).unwrap(),
			lname:from_value_opt(r[2].clone()).unwrap(),
			address:from_value_opt(r[3].clone()).unwrap(),
			address2:from_value_opt(r[4].clone()).unwrap(),
			city:from_value_opt(r[5].clone()).unwrap(),
			state:from_value_opt(r[6].clone()).unwrap(),
			zip:from_value_opt(r[7].clone()).unwrap(),
			email:from_value_opt(r[8].clone()).unwrap(),
			phone:from_value_opt(r[9].clone()).unwrap(),
			manager_id:from_value_opt(r[10].clone()).unwrap(),
			user_id:from_value_opt(r[11].clone()).unwrap(),
			location_1_id:from_value_opt(r[12].clone()).unwrap(),
			location_2_id:from_value_opt(r[13].clone()).unwrap(),
			location_3_id:from_value_opt(r[14].clone()).unwrap(),
			position:from_value_opt(r[15].clone()).unwrap(),
			facility_name:from_value_opt(r[16].clone()).unwrap(),
			speciality:from_value_opt(r[17].clone()).unwrap()
		};
```
it works, found with help of @defuz, from Ru Rustlang community chat: https://gitter.im/ruRust/general?at=56524051541ec57a66e30365

**Comment by blackbeam** [comment]
Не думаю что это лучшее решение.
Вызовы `clone` спровоцируют дополнительное выделение памяти для всех текстовых ячеек строки.
from_row обладает потребляющим API именно с той целью, чтобы избавиться от явно лишних выделений.

Думаю более производительным решением будет просто изменить порядок присвоения значений полям структуры на обратный (уверен что в большинстве редакторов есть комбинация клавиш для этого):
```rust
let contact = Contact {
    speciality: from_value(row.pop().unwrap()),
    facility_name: from_value(row.pop().unwrap()),
    ...
```

Что касается использования from_value_opt, то он нужен только когда разработчик не уверен что он может получить из строки и это наверняка не ваш случай. Если типы полей структуры определены адекватно схеме БД (нет попыток извлеч, например, число из текстовой ячейки, нет попыток извлеч, например, u8 из BIGINT, все nullable поля в структуре определены как Option<_>), то from_value как никогда не запаникует так и никогда не пройдет через unsafe-блок.

**Comment by defuz** [comment]
@e-oz @blackbeam 
Чтобы не менять порядок выполнения, можно воспользоватся `into_iter`:
```rust
let mut iterator = row.into_iter();
let contact = Contact {
    id: from_value(iterator.next().unwrap()),
    fname: from_value(iterator.next().unwrap()),
    ...
```

**Comment by blackbeam** [comment]
@e-oz, прекрасное решение.

Пожалуй я оберну ошибочный результат `from_value_opt` и `from_row_opt` в дополнительные вырианты `MyError`, чтобы не вызывать лишних конфузий.

@e-oz @defuz, спасибо вам.
К сожалению фидбеков по API достаточно мало и каждый подобный Issue на вес золота.

**Comment by e-oz** [comment]
(I'll stick with English, for future readers :))

@defuz yes, with iterator it works. With pop() it wasn't working just because I didn't know about reverse-order (my mistake), but iterator looks more intuitive. Thank you very much again. 

@blackbeam thanks for note about from_value/_opt. With just `from_value` code looks more clear.
