### ISSUE TITLE
DriverError

### ISSUE THREAD

**Issue by QMHTMY** [blackbeam/rust-mysql-simple#290]
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: DriverError { Could not connect to address `root:3306': failed to lookup address information: Name or service not known }

    let url = "mysql://root:#*Shieber2021@localhost:3306/test";
    let opts = Opts::from_url(url).unwrap();
    let pool = Pool::new(opts).unwrap();
    let mut conn = pool.get_conn().unwrap();

I am wondering if the characters "#*" in password caused such an error?

**Comment by blackbeam** [comment]
Hi. Yeah, special chars in URLs should be urlencoded.
