### ISSUE TITLE
Please remove unsafe code

### ISSUE THREAD

**Issue by e-oz** [blackbeam/rust-mysql-simple#30]
In source code I found just 1 kind of unsafe usage - FromRow implementation. I tried to remove it (along with mem::forget) and code compiles successfully. Please consider to remove this part - Rust will clean up memory itself, I believe.

**Comment by blackbeam** [comment]
Did you try `make test`?
I think this change will break `should_return_error_if_could_not_convert`.

**Comment by e-oz** [comment]
No, I didn't but in my implementation it's replaced by

```rust
			_ => {
				Err(row)
			}
```
and I think it will return Error.

**Comment by blackbeam** [comment]
Yeah. I should rename this test :smile:

As mentioned in `FromRow::from_row_opt` docs:
>  Will return `Err(row)` if could not convert `row` to `Self`

If i remove unsafe block and `mem::forget` it will always return empty `Vec` instead of original row.

I saw this pattern somewhere in standard library.

**Comment by e-oz** [comment]
I really doubt if somebody needs one more copy of row as a result of this function.. Maybe I just don't know some cases.

**Comment by blackbeam** [comment]
`FromRow::from_row_opt` is a fast and non panicking way to check that row is convertible to some type.
For example:
```rust
match from_row_opt::<(u8, u8)>(row) { // row is consumed here so you have no row anymore
    Ok((x, y)) => println!("Got ({}, {})", x, y),
    Err(row) => {
        // Here row is not a copy but original row passed to from_row_opt
        // and there is no other way to get it instead of copying which might be expensive
    }
}
```

**Comment by e-oz** [comment]
And as `from_row` is just wrapper on `from_row_opt`, all our code is unsafe. It's very frustrating.
Ok, what done is done.

**Comment by e-oz** [comment]
non-panicking code with "unsafe" is some kind of rust-humor :)

**Comment by blackbeam** [comment]
@e-oz, вы, признаться честно, обеспечили мне бессонную ночку.
Я пришел к выводу, что в рамках библиотеки этот unsafe-блок безопасен, однако если кто-то неосторожно реализует `FromValue` для своего типа, потребляющего `Value::Bytes` то может закончить с double free.
Я всеже считаю этот сценарий маловероятным т.к. даже с учетом использования `FromValue` для своего типа, прохождение `from_row_opt` через unsafe-блок мне видится крайне редким.

Однако теперь я уверен что от этого кода необходимо избавиться.
С этим, в свою очередь, есть проблемы, т.к. я не хочу терять не отсутствие лишних аллокаций не отсутствие лишних проверок, но надеюсь что какой-то адекватный дизайн придет мне в голову в ближайшее время.

Спасибо за репорт.

**Comment by e-oz** [comment]
Прошу прощения. Я и сам не спал :) Однако считаю даже небольшую вероятность вероятностью, и пока она вероятна, она будет происходить. Не недооценивайте изворотливость программистов! :)

**Comment by defuz** [comment]
@blackbeam, все это звучит немного странно. Мы можем обсудить это в чате? https://gitter.im/ruRust/general
