### ISSUE TITLE
Explicitly close database connection

### ISSUE THREAD

**Issue by JakobST1n** [blackbeam/rust-mysql-simple#308]
Hi, I cannot find any documentation on when a connection closes. I see that a pool will stop when it is no longer referenced, but what about "normal" `Conn`?
Is there something _like_ `Conn::close` that will close the connection? From what I understood from the docs, the method with that signature does not.

**Comment by blackbeam** [comment]
Oh, sorry. `COM_QUIT` is executed in `impl Drop for Conn`. I'll update the docs.
