### ISSUE TITLE
Get the actual warning messages from the database

### ISSUE THREAD

**Issue by ahmedriza** [blackbeam/rust-mysql-simple#313]
We can get the number of warnings from https://docs.rs/mysql/22.1.0/mysql/struct.Conn.html#method.warnings. Is there a way to get the actual warning messages?

The background is that I am using https://docs.rs/mysql/22.1.0/mysql/struct.LocalInfileHandler.html and when the file load fails for some reason (e.g. it couldn't parse the file properly), the database will issue warnings without raising errors and it will be very useful to see what they are in order to diagnose what went wrong.

**Comment by blackbeam** [comment]
Hi.
Have you tried to look into the info (`Conn.info_str`) or into the output of a `SHOW WARNINGS`?

**Comment by ahmedriza** [comment]
Thanks @blackbeam for the pointers.  

Ah, realised that I'm actually using `mysql_async`.  Nevertheless, issuing a `SHOW WARNINGS` afterwards does produce the relevant warnings.  So, I guess I could just call `SHOW WARNINGS`, if the number of warnings is non-zero on the connection.  

Since I'm holding on to connection from the Pool, I guess that it is safe and no other query would have been executed on that connection in between.

**Comment by blackbeam** [comment]
> Since I'm holding on to connection from the Pool, I guess that it is safe to issue the second SHOW WARNINGS query, and no other query would have been executed on that connection in between.

Yeah, this is safe.
You should be careful only in the case when queries are executed directly on a pool (via the Query trait)

**Comment by ahmedriza** [comment]
Cheers @blackbeam
