### ISSUE TITLE
Example code does not work for me

### ISSUE THREAD

**Issue by conormdowney** [blackbeam/rust-mysql-simple#314]
Im just trying to run the simple example to connect to a database but im getting an error on the line trying to create a new Pool. Here is my code 

```
use mysql::*;
use mysql::prelude::*;

fn main() {
    println!("Hello, world!");
    let url = "db-string";
    let pool = Pool::new(url)?;
}
```

Im getting an error on the last line. it says: 

```
error[E0277]: the trait bound `Opts: From<&str>` is not satisfied
   --> src/main.rs:7:26
    |
7   |     let pool = Pool::new(url)?;
    |                --------- ^^^ the trait `From<&str>` is not implemented for `Opts`
    |                |
    |                required by a bound introduced by this call

```

Im pretty new to rust so can someone help me with this?

**Comment by blackbeam** [comment]
@conormdowney, hi.
Sorry, but looks like the example code wasn't properly updated.
Following should work:

```rust
```

**Comment by conormdowney** [comment]
Thanks for the update. Getting a different error now:

```
let pool = Pool::new(opts)?;
  | |                               ^ cannot use the `?` operator in a function that returns `()`
```

**Comment by conormdowney** [comment]
Thanks for the update. Im getting a different error now with the code you gave me: 

```
fn main() {
5  | |     println!("Hello, world!");
6  | |     let opts = Opts::from_url("mysql://rotogro:Roto123!@localhost:3306/db")?;
7  | |     let pool = Pool::new(opts)?;
   | |                               ^ cannot use the `?` operator in a function that returns `()`
```

**Comment by blackbeam** [comment]
This one already answered [here](https://github.com/blackbeam/rust-mysql-simple/issues/296#issuecomment-951739645).

**Comment by blackbeam** [comment]
This result is just a type alias to `std::result::Result` defined here: https://github.com/blackbeam/rust-mysql-simple/blob/6d856627425a19a854f13324bb6cdc93f7eb857e/src/error/mod.rs#L350

It's a usual practise for libraries and modules to define it's own type aliases to Result (eg std::Io::Result, std::fmt::Result)
