### ISSUE TITLE
How to fetch datetime

### ISSUE THREAD

**Issue by e-oz** [blackbeam/rust-mysql-simple#33]
Please show an example how to fetch datetime field. What type I should use in structure declaration?

**Comment by blackbeam** [comment]
`FromValue` is implemented for the `TimeSpec` type of *time* crate so this should work:
```rust
use time::Timespec;
...
let timespec = from_value::<Timespec>(row.pop());
```

Just looked at *rust-postgres* for a reference and i think i should implement `FromValue` for some types of *crono* crate. For now you can do something like this:
```rust
use time::Timespec;
use chrono::*;
...
struct MyStruct {
    datetime: DateTime,
    ...
}
...
    let ts = from_value::<Timespec>(row.pop());
    ...
    return MyStruct {
        ...
        datetime: DateTime::from_utc(NaiveDateTime::from_timestamp(ts.sec, ts.nsec), ...),
```

**Comment by blackbeam** [comment]
Your issue revealed another bug, so thanks again!
You definitely should upgrade *mysql* crate version to v1.2.0.

**Comment by e-oz** [comment]
Thank you.

**Comment by evbo** [comment]
> `FromValue` is implemented for the `TimeSpec` type of _time_ crate so this should work:

Is this still how you fetch a datetime column value? And what is the process for inserting a datetime type (same process in reverse?)?

**Comment by blackbeam** [comment]
@evbo, mysql_common supports `chrono` as well as  `time` 0.2 and 0.3 (see [here](https://docs.rs/mysql_common/latest/mysql_common/#crate-features))
