### ISSUE TITLE
Shouldnt params replace values marked with ':'?

### ISSUE THREAD

**Issue by JulianWogersien** [blackbeam/rust-mysql-simple#370]
I have this piece of code
![Screenshot from 2024-01-30 12-42-19](https://github.com/blackbeam/rust-mysql-simple/assets/31437161/85f9d70b-5782-453c-8886-83e94dd9de5c)

However This results in this error
![Screenshot from 2024-01-31 09-08-05](https://github.com/blackbeam/rust-mysql-simple/assets/31437161/aeb5290e-dc61-418b-8a73-b19762f33823)

What exactly is wrong here?
Afaik i did it like the example in the docs

**Comment by blackbeam** [comment]
Hi.

The naming rules was overlooked:

* parameter name must start with either `_` or `a..z`
* parameter name may continue with `_`, `a..z` and `0..9`
