### ISSUE TITLE
Obtaining chunked results

### ISSUE THREAD

**Issue by Fiedzia** [blackbeam/rust-mysql-simple#40]
I can't figure out how to get results grouped into chunks of specified size. Is it possible  without implementing it myself?

**Comment by blackbeam** [comment]
Do you mean some kind of API-level pagination?
Or maybe something missed on client-server protocol level?

Could you please provide more info, or maybe an example in other (lib / lang) of what are you (trying to do / looking for)?

**Comment by Fiedzia** [comment]
I am not familiar with mysql protocol, so I am not sure how it would interact with it, but in pseudocode this is what I want to do:
```
for rows in conn.prep_exec("select foo from table").chunks(200) {
    process_chunk(rows);  //where rows is something iterable that contains up to 200 rows 
}
```

**Comment by blackbeam** [comment]
Looks like something related to iterators in general.
I think [Itertools](https://bluss.github.io/rust-itertools/doc/itertools/trait.Itertools.html#method.chunks_lazy) will allow you to do something like this (*pseudocode*):

```rust
use itertools::Itertools;

for chunk in conn.prep_exec("select foo from table").chunks_lazy(200) {
    process_chink(chunk);
}
```
