### ISSUE TITLE
Benches

### ISSUE THREAD

**Issue by tafia** [blackbeam/rust-mysql-simple#41]
Is there any bench available?

In particular, I'd like to see if we could try changing the [`write_paquet`](https://github.com/blackbeam/rust-mysql-simple/blob/master/src/io.rs#L253-L256) part (for large paquets) to:

```rust
// ...
let mut writer = Vec::with_capacity(4); // could probably be out of the chunks loop
try!(writer.write_le_uint_n(chunk_len as u64, 3));
try!(writer.write_u8(seq_id));
// try!(writer.write_u8(chunk));
try!(self.write_all(&writer[..]));
// instead of copying the entire chunk into the writer, 
// we could write it directly to the stream
try!(self.write_all(chunk));
// ... 
```

On my test it *seems* to be better but I am really not certain.

**Comment by blackbeam** [comment]
Yeah.
You should switch to nightly in your multirust, then run `make bench`.
It will run benches for all feature combinations.
But this, obviously, will work only on linux or mac.

**Comment by tafia** [comment]
Thanks!
I've just tried cargo bench.
