### ISSUE TITLE
"Will not check or fix connection health."

### ISSUE THREAD

**Issue by e-oz** [blackbeam/rust-mysql-simple#42]
After [this](https://github.com/blackbeam/rust-mysql-simple/commit/e15cf370bc7237a36ad56bf8e8112e43ee15aae5) change I have to stick to old version of this lib, where connection health was checked. Please consider to create some kind of flag in settings to use that boolean argument you introduced in private function `_get_conn `. Or, if it exists, please add information to docs. 
Otherwise it will fail again by timeout after each night without visitors.

**Comment by blackbeam** [comment]
Sorry for that.
I'll fix this soon.

**Comment by e-oz** [comment]
Thank you very much, I didn't expect it will require so large amount of code. Thank you, you are the best!

**Comment by e-oz** [comment]
@blackbeam tested and works great - thank you very much again. Changes in 2.x are great!
