### ISSUE TITLE
Connect timeout

### ISSUE THREAD

**Issue by Fiedzia** [blackbeam/rust-mysql-simple#43]
Please add a way to define connection timeout, so that in case of db not responsing, an error is returned. Currently it just hangs forever.

**Comment by Fiedzia** [comment]
This sets read and write timeouts, not connect timeouts. connecting may still just hang.

**Comment by blackbeam** [comment]
I believe that OS defines some connection timeout at least for TCP.
Maybe in your case connection was established but client couldn't read handshake from server? Read timeout should handle it.

**Comment by blackbeam** [comment]
Anyway i will reopen it.
Could you please check an impact of read/write timeout for your case if it is possible?

**Comment by Fiedzia** [comment]
read and write define timeouts on read and write, but have nothing to do with timeout on connect.
The default value for that is defined by os (and absurdly high for most cases), but it can be overriden - this is an example:
https://github.com/Fiedzia/net2-rs/commit/500bb458ca77e129537c26b934ab039e6bfb5fa9

**Comment by sapsan4eg** [comment]
I agree with Fiedzia, i have long sql queres 10-30 minutes. But i need know when i cannot connect to server first time. Current i wait about 50-60 second. It's too long.

**Comment by Tokap** [comment]
Has there been any progress made regarding a more direct way to set initial connection duration other than manually overriding one's OS defaults? This would be an extremely useful feature addition.

**Comment by blackbeam** [comment]
Ah! I almost forgot about that issue.

Only solution i found is unix-only but i think it should be added.
I'll try to publish next week.

**Comment by Tokap** [comment]
I appreciate your prompt response and look forward to seeing your solution.

**Comment by blackbeam** [comment]
`tcp_connect_timeout` option and `tcp_connect_timeout_ms` url parameter is implemented and available in v9.1.0.

**Comment by Fiedzia** [comment]
awesome

**Comment by Tokap** [comment]
Very much appreciated @blackbeam. Thanks!
