### ISSUE TITLE
Using Pool::new("mysql://user:pass@any_host_except_local:port/database") on windows doesn't work properly.

### ISSUE THREAD

**Issue by Rafagd** [blackbeam/rust-mysql-simple#44]
Hadn't time to check the code yet, but when I was compiling a test I found this error.

I tried to use Pool::new("mysql://user:pass@192.168.0.14:3306/database") on Debian and it worked fine, but as soon as I've recompiled it on Windows, IP address was always defaulting to localhost (127.0.0.1).

It also worked on Windows after I changed the string to a manually created Opts.

**Comment by feellin** [comment]
this problem appears on CentOS and MAC OS too.

**Comment by blackbeam** [comment]
Could not reproduce but i think problem occurs [here](https://github.com/blackbeam/rust-mysql-simple/blob/master/src/conn/opts.rs#L473). Could you please give me your exact connection string?

**Comment by Rafagd** [comment]
String was  Pool::new("mysql://user:pass@192.168.0.14:3306/database"), just changing user, pass and database to the correct values. Also, it did work on Debian, but not on Windows.

**Comment by blackbeam** [comment]
BTW, did you try to percent-encode your password? I believe it should be encoded to escape possible reserved characters.

**Comment by Rafagd** [comment]
There were no fancy characters, only alphanumeric.

**Comment by Rafagd** [comment]
I'll try to make a reproducible example later.

**Comment by blackbeam** [comment]
@Rafagd, the issue was fixed automatically because of a commit message. Could you please try to reproduce it on v4.0.0 and reopen if reproducible?

**Comment by Rafagd** [comment]
Sure.
