### ISSUE TITLE
How can I debug `Could not convert row to (T1 .. T7)`?

### ISSUE THREAD

**Issue by opensourcegeek** [blackbeam/rust-mysql-simple#45]
I'm quite new to Rust and slowly getting the hang of language, one of the things I'd like to do is number crunching with Rust (instead of using C++) but some of the data is in mysql database. As a first step I need to get all that data out, I have started tinkering with this library - but I get a run time error as mentioned in the subject. Digging into the code I'm not quite sure if I understand it, what is the usual cause for this issue? Any pointers would be greatly useful.

**Comment by blackbeam** [comment]
It should not be a problem. This error means that type of a value in some cell of your row could not be converted into corresponding type of your rust tuple. May be you are trying to convert NULL into some type not wrapped into an `Option.
