### ISSUE TITLE
Appropriate for use with libmysqld?

### ISSUE THREAD

**Issue by photex** [blackbeam/rust-mysql-simple#49]
Howdy!

Before I were to get started attempting to add support for embedded mysql; is there any reason this wouldn't work with rust-mysql-simple?

And barring any technical problems; what about licensing if I wanted to link statically?

**Comment by blackbeam** [comment]
Hi!

TIL that libmysqld exists 😅
> is there any reason this wouldn't work with rust-mysql-simple?

If you can't connect to it via TCP or socket, then it won't work. I am not sure what you need to do to make it work because i know nothing about libmysld.

> And barring any technical problems; what about licensing if I wanted to link statically?

Current license is MIT. It permits static linking AFAIK.

**Comment by seeekr** [comment]
just a FYI for @photex (and others if interested) -- libmysqld (embedded MySQL) is going to be removed in MySQL 8.0: http://mysqlserverteam.com/mysql-8-0-retiring-support-for-libmysqld/
(And being deprecated for the 5.7 series.) Probably not worth building anything on top of it / for use with it any more. Cheers.
