### ISSUE TITLE
Purpose of '' in into_str()

### ISSUE THREAD

**Issue by frjonsen** [blackbeam/rust-mysql-simple#51]
What exactly is the reason '' are added around strings [into_str()](https://github.com/blackbeam/rust-mysql-simple/blob/938c2d052bf9a3e5235e3aa05e090b02992855ca/src/value.rs#L146)? I'm storing names in a table, and essentially end up having to slice every single one to remove the apostrophes. Or is there some other preferred way of getting strings when parsing a row, which doesn't add the apostrophes?

**Comment by blackbeam** [comment]
The only way to get string from `my::Value` is using functions based on `FromValue` trait.
Something like this:

```rust
struct User {
    id: u32,
    name: String,
};

let row = ...; // SELECT id, name FROM users
let (id, name) = my::from_row(row);
return User {
    id: id,
    name: name,
};
```

The purpose of `Value::into_str` is to construct raw SQL queries, but i am almost sure that no one really using it.
I think i should deprecate it.
