### ISSUE TITLE
Straightfoward way to run queries

### ISSUE THREAD

**Issue by Fiedzia** [blackbeam/rust-mysql-simple#52]
There are many times where I just want to get one row, for queries like "select username where id=3".

It would be nice to have shortcut for that like:

let username = pool.get_row(query).unwrap()[0]

without writing 10 lines to get through all map calls, or writing that:

let number = pool.prep_exec("select 1", ()).unwrap().next().unwrap().unwrap().unwrap()[0].clone();

**Comment by blackbeam** [comment]
Hi! I am on vacation atm. I will add something like `first` and `first_exec` in a few weeks.

**Comment by Fiedzia** [comment]
Thanks, have a nice holiday

**Comment by blackbeam** [comment]
In v5.2.0

**Comment by philippludwig** [comment]
Sadly `first` and `first_exec` are not documented.

**Comment by blackbeam** [comment]
@philippludwig, here is the docs, or am i missing something?

first: https://docs.rs/mysql/15.0.0/mysql/struct.Conn.html#method.first
first_exec: https://docs.rs/mysql/15.0.0/mysql/struct.Conn.html#method.first_exec
