### ISSUE TITLE
DateTime parsing is broken

### ISSUE THREAD

**Issue by valarauca** [blackbeam/rust-mysql-simple#66]
Issue:

MySQL DATE allows for 0th day of the month. While `chrono::NaiveDate` does not.

To Recreate:

MySQL Packet: https://s21.postimg.io/5wuv01pzb/found_you.png

The field `Value::Bytes([50, 48, 49, 54, 45, 48, 55, 45, 48, 48])` (2016-07-00) cannot be parsed to a `chrono::NaiveDate`. Nothing in `rust-mysql-simple` prevents this, the issue is `chrono::NaiveDate::from_ymd_opt(3)` returns `Option::None` with the arguments `2016,7,0`. It'll return a `date out of range` issue.

Solution:

I've created a pull request to solve this issue

https://github.com/blackbeam/rust-mysql-simple/pull/65

**Comment by blackbeam** [comment]
I'm closing it. See comment on #65.

**Comment by westy92** [comment]
A way to get the desired value (`2023-00-00`) would be converting it to a string when it's sent over the wire:

```mysql
SELECT DATE_FORMAT(date, '%Y-%m-%d')
FROM table_name;
```

Ideally, this library would allow parsing MySQL Dates into Strings.
