### ISSUE TITLE
Use native-tls instead of openssl

### ISSUE THREAD

**Issue by Diggsey** [blackbeam/rust-mysql-simple#67]
The openssl library is a PITA to build on windows, the native-tls library uses the host's tls implementation (`schannel` on windows, `security-framework` on osx and `openssl` on other platforms)

**Comment by blackbeam** [comment]
Can't find native-tls in crates.io 😞

**Comment by DenisKolodin** [comment]
It's a good idea, but `native-tls` is quite young. I think we have to keep this issue till `native-tls` released.

**Comment by zoumi** [comment]
Some people have offered to provide OpenSSL binary distributions for selected operating systems. 

    https://indy.fulgan.com/SSL/
    https://wiki.openssl.org/index.php/Binaries

**Comment by TerraX-net** [comment]
In https://github.com/blackbeam/mysql_async you could use https://crates.io/crates/tokio-rustls
and for rust-mysql-simple you could use https://crates.io/crates/rustls .

rustls is built on top of https://github.com/briansmith/ring and https://github.com/briansmith/webpki .
ring is a fork of Google's Bo**ring**ssl, which aims to rewrite as much as possible (and meaningful) in Rust. rustls can even be used with hyper, the most popular rust http library, with https://crates.io/crates/hyper-rustls . With using the system's native TLS implemenation we would not profit from Rust's advantages to have a secure TLS implementation.

**Comment by Thomspoon** [comment]
sfackler to the rescue: https://github.com/sfackler/rust-native-tls
