### ISSUE TITLE
Problem with `select @@slow_query_log`

### ISSUE THREAD

**Issue by franleplant** [blackbeam/rust-mysql-simple#69]
Hi!
    

Im trying to read if the mysql slow query log is enabled or not.
Here is the program and this is the [repo](https://github.com/franleplant/rusted-mysql-test):

```rust
#[macro_use]
extern crate mysql;

use mysql as my;
use mysql::value::from_row;

fn main() {
    let pool = my::Pool::new("mysql://root:root@localhost:3306").unwrap();
    let mut stmt = pool.prepare("SELECT ?").unwrap();

    for result in stmt.execute(("@@slow_query_log",)).unwrap() {
        let row = result.unwrap();
        let row_tuple = from_row::<String>(row);
        println!("TUPPLE ROW: {}", row_tuple);
    }
}
```

This program compiles and runs but it prints this 
```
@@slow_query_log
```

Instead of the expected value which is 0 or 1.

Here is how that same query looks in mysql cli:

```sh
mysql> select @@slow_query_log;
+------------------+
| @@slow_query_log |
+------------------+
|               0 |
+------------------+
1 row in set (0.00 sec)
```

I suspect that the lib is only telling me about the first "row" in the previous example.

Any ideas?

Thanks a lot in advance!
Fran

**Comment by blackbeam** [comment]
Mysql protocol defines types that driver can send via binary protocol (i.e. prepared statement). You can read documentation [here](https://dev.mysql.com/doc/internals/en/com-stmt-execute.html).

You can send only [defined set of types](https://dev.mysql.com/doc/internals/en/binary-protocol-value.html) which looks like types that you can actually store in cells.

Rust strings is encoded as `ProtocolBinary::MYSQL_TYPE_STRING` so if you execute `SELECT ?` with `@@slow_query_log` as a parameter you will get `SELECT '@@slow_query_log'` as an actual query, which obviously not equals to desired `SELECT @@slow_query_log`.

I believe that you just can't pass variable name via statement parameter.

As a possible solution:

1. First option is to use text protocol via `PooledConn::query("SELECT @@slow_query_log")`.
2. Or, if your server version allows, you can use `performance_schema` table: `SELECT * FROM performance_schema.global_variables WHERE VARIABLE_NAME = ?`.

**Comment by franleplant** [comment]
Excelente explanation, thanks a lot for your time!

**Comment by percona-csalguero** [comment]
:+1:
