### ISSUE TITLE
URL ParseError { invalid port number } if password contains "?"

### ISSUE THREAD

**Issue by Tiega91** [blackbeam/rust-mysql-simple#78]
`let pool = mysql::Pool::new("mysql://user:password?@localhost:3306/test").unwrap();`

throws the following error:
```
thread 'main' panicked at 'URL ParseError { invalid port number }', 
...\mysql-7.1.2\src\conn\opts.rs:580
```
It doesn't matter at which position the "?" is, it will always throw the error.
My specs:

```
D:\Rust_Training>rustc --version
rustc 1.12.1 (d4f39402a 2016-10-19)

D:\Rust_Training>cargo --version
cargo 0.13.0-nightly (109cb7c 2016-08-19)

 Fresh mysql v7.1.2
```

**Comment by blackbeam** [comment]
I believe there was related issue already, but i couldn't find it..

Anyway. You should urlencode some characters according to RFC 3986.
I.e. something like this should work:

```rust
let pool = mysql::Pool::new("mysql://user:password%3F@localhost:3306/test").unwrap();
```

**Comment by blackbeam** [comment]
Closing it.
Feel free to reopen if needed.

**Comment by MTRNord** [comment]
Hm I got a `#` in my password and urlencoding doesnt help either. Other Ideas?

**Comment by blackbeam** [comment]
Issue may be related to the `url` crate which is used for URL parsing. I'll look into it tomorrow.

**Comment by blackbeam** [comment]
> Hm I got a # in my password and urlencoding doesnt help either.

Looks like there is no issue, because this program:
```rust
extern crate mysql as my;

fn main() {
    let opts = my::Opts::from("mysql://root:pass%23word@localhost/");
    println!("password: {:?}", opts.get_pass());
    let pool = my::Pool::new(opts).unwrap();
    let row = pool.first_exec("SELECT 'foo'", ()).unwrap();
    println!("{:?}", row);
}
```
gives this output:
```
password: Some("pass#word")
Some(Row(Bytes("foo")))
```
So urlencoded `#` was parsed correctly and connection to the server was successful.

> Other Ideas?

Note that your shell may interpret `#` symbol as a start of a comment. I.e.:
```sh
mysqladmin -uroot -p password pass#word
```
The password of the root user will be `pass` instead of `pass#word`.
To fix this you'll need to quote password:
```sh
mysqladmin -uroot -p password 'pass#word'
```
Please make sure that it's not you case and if it isn't please send me an output of the code above but with your connection string.

**Comment by MTRNord** [comment]
I think the reason is that I didn't know of the 
`let opts = my::Opts::from("mysql://root:pass%23word@localhost/");`
that line isn't in the example I will try that.

**Comment by MTRNord** [comment]
my bash doesn't make the # to a comment but my # is at the end of the password so my string looks like `mysql://root:password#@localhost:3307`

**Comment by MTRNord** [comment]
Oh I think the usage of `format!()` is my problem it creates `"mysql://\"root\":\'\"password#\"\'@\"127.0.0.1\""`

**Comment by blackbeam** [comment]
Anyway please show me the output of this code:
```rust
extern crate mysql as my;

fn main() {
    println!("url: {}", <your exact connection string here>);
    let opts = my::Opts::from(<your exact connection string here>);
    println!("password: {:?}", opts.get_pass());
    let pool = my::Pool::new(opts).unwrap();
    let row = pool.first_exec("SELECT 'foo'", ()).unwrap();
    println!("{:?}", row);
}
```

**Comment by MTRNord** [comment]
```
mtrnord@riot:~/rust/IMAPServer-rs$ RUST_BACKTRACE=1 cargo run
    Finished dev [unoptimized + debuginfo] target(s) in 0.1 secs
     Running `target/debug/IMAPServer`

url: mysql://root:password#@127.0.0.1/
thread 'main' panicked at 'URL ParseError { invalid port number }', /home/mtrnord/.cargo/registry/src/github.com-1ecc6299db9ec823/mysql-11.3.0/src/conn/opts.rs:582
note: Run with `RUST_BACKTRACE=1` for a backtrace
```

**Comment by blackbeam** [comment]
Looks like `#` isn't url-encoded. First line of output should be:
```
url: mysql://root:password%23@127.0.0.1/
```

**Comment by MTRNord** [comment]
I will try to urlencode it first. one sec.

**Comment by MTRNord** [comment]
Finally got it my url encoding wasn't doing the expected. switching to the urlencoding crate did the job :) issue can be closed. It was broken urlencoding on my side. Still thanks for the help

**Comment by blackbeam** [comment]
No problem.

**Comment by evbo** [comment]
...Still waiting for the day when type safe languages can save us from poorly formatted strings. 

Until then, here's a good urlencoding crate for this:
https://docs.rs/urlencoding/latest/urlencoding/
