### ISSUE TITLE
Some(NULL) Should Be Convert to None or Some Default Value

### ISSUE THREAD

**Issue by asteriskTheServer** [blackbeam/rust-mysql-simple#79]
I can see see this being fairly useful unless of coarse I am missing some feature in the library which makes this easy already and I haven't found it. 

The main issue I am facing is the when one does row.take on mysql row where the value is `Some(NULL)` it tries to bind it to some type be it a String or a i32 or whatever data type and will produce the error  `Could not retrieve <type> for value ` which makes sense from the code's perspective, but in terms of usability I don't think this makes sense. If I have a NULL it should be the rust's loose equivalent of a NULL, namely None. Of coarse if I am misunderstanding the why here please let me know.

**Comment by blackbeam** [comment]
It should be easy:
```rust
let column_value: Option<String> = row.take("name_of_a_column_that_might_be_NULL").unwrap();
               // ^^^^^^^^^^^^^^ magic is here
```

**Comment by asteriskTheServer** [comment]
@blackbeam Sorry, not enough coffee this morning but that is super obvious. :(

**Comment by asteriskTheServer** [comment]
Hmmm , @blackbeam this actually doesn't work I'll provide a more specific example sample of what I am doing. 

```rust

pub struct Person {
     name: String, 
     nickname: Option<String>
}

impl mysql::FromRow for Person {
      fn from_row(mut row: mysql::Row) -> Self {
            Person {
                 name: row.take<String, &str>("name").unwrap(), // works fine and returns a string. 
                 nickname: row.take<String, &str>("nickname") 
            }
      }
}

Still tells me that it is unable to bind <type> to Value in this case a string. Furthermore, you can assume that the data type in the database is a varchar. Also, it does seem like the data type for nickname is Option<String>, but it doesn't want to actually convert the value.

**Comment by blackbeam** [comment]
This should work:
```rust
Person {
    // ...
    nickname: row.take("nickname").unwrap(),
}
```

Let's make it clear:

Your nickname column value could be NULL, so corresponding rust type for nickname column value is `Option<String>`.

`Row::take` signature is `fn<T, A>(&mut self, A) -> Option<T>`. `T` in this signature is the type of a column value, and `Option` in return type representing the fact that column value could be already taken from row (which is usually obvious so it's almost always safe to `unwrap` it immediately).

So your call to `row.take` should look like this `row.take::<Option<String>, _>("nickname").unwrap()` but in your case compiler can infer the type for `T` so you can just write `nickname: row.take("nickname").unwrap()`

**Comment by asteriskTheServer** [comment]
@blackbeam Ohhhhh okay, I think understand now. I appreciate you taking the time to answer my question despite them being not really being library specific. Thanks.
