### ISSUE TITLE
How to work with dynamic rows / rows that i do not know

### ISSUE THREAD

**Issue by cars10** [blackbeam/rust-mysql-simple#81]
Is there a way to use  `mysql::from_row(row)` for tables that i do not know?
Basically i want to show whats in a certain database, without knowing the structure and number of columns it has. (i therefore can not implement `from_row` for my struct)

**Comment by blackbeam** [comment]
You can get column names of dynamic row using `QueryResult::column_indexes`.
Also you can get column types using `QueryResult::columns_ref`.
Also raw row (i.e. sequence of column values) could be unwrapped using `Row::unwrap`.
