### ISSUE TITLE
Support for a Idiomatic way to determine if there are no rows in QueryResults

### ISSUE THREAD

**Issue by TheServerAsterisk** [blackbeam/rust-mysql-simple#82]
As far as I can tell the only way to determine if there are any results from a select statement is to clone the query result and then execute count. Unfortunately, size_hint isn't useful here either as 1 result will return (0,None) and it will also return (0, None) if there are no results.  Also, it seems to be the case that more_results_exists() will output true as well even if the set is empty. 

Alternatively one can just do a Count(*) query and then use that returned value as means to determining if there are no results are not. Whether this is the better solution or not I am not entirely sure. 

Ideally, it would great if there was a cheaper and idiomatic solution than cloning QueryResult.

**Comment by blackbeam** [comment]
AFAIK the only way, from protocol perspective, to get count of rows in result set is to consume result set and count it's rows, so i think your options are:
1. If you need to count rows in a result set as well as rows itself then your option is to make a query and iterate `QueryResult` to count rows and to use values.
1. If you only need to count rows in your query then `first_exec("SELECT COUNT...` should do it.

**Comment by TheServerAsterisk** [comment]
Hmmm, I see I am not overly familiar with the mysql protocol, but it also seems that PDO has the same limitation as well. Typically, the response is to count the length of the array, or to follow up that query with a Count(*) or I guess you alias it and include it in the statement or use the FOUND_ROWS() function which utilizes the mysql cache. Regardless, thanks for your help.
