### ISSUE TITLE
Would it be possible/reasonable to add an iron feature where use iron::typemap::Key is implemented? 

### ISSUE THREAD

**Issue by TheServerAsterisk** [blackbeam/rust-mysql-simple#83]
With the [persistent](https://github.com/iron/persistent) crate for iron one requires to implement the Key trait. While one could just create a wrapper struct it would be nice if this was already implemented as a feature. However, I can understand if this was not wanted as well.

**Comment by blackbeam** [comment]
I can't see a reason to use any of mysql's types as a key, but maybe I'm missing something.
Could you provide an example?

**Comment by TheServerAsterisk** [comment]
No, I don't think there is example. I was hoping I  could achieve the following 

```
impl Key for Pool {type Value = Conn } 
```

So the pool is abstracted away and a connection from the pool, however, looking at the source code for persistent it is not possible. Even then I question why I thought this would be a good idea at the time of writing this issue. Especially considering #39 where it was more or less stated that one should favor using the pool for caching reasons as suppose to grabbing individual connections.
