### ISSUE TITLE
WHERE IN conditions in queries with Vec<usize> parameter

### ISSUE THREAD

**Issue by sebasmagri** [blackbeam/rust-mysql-simple#85]
Hi!

Some days ago I asked in [u.r.o](https://users.rust-lang.org/t/rust-mysql-simple-and-where-in-queries-with-vec-usize/8735) about the right way to to a `WHERE IN` condition in a query while holding all the options in a `Vec<usize>`, but I have not still get an answer neither found a way to do it.

Is this supported by this crate? What's the right way to do it?

**Comment by blackbeam** [comment]
Named placeholders is just a sugar for mysql's `?` placeholder so no magic happens.
I think following should work:

```rust
let placeholders = (0..ids.len()).map(|_| String::from("?")).collect::<Vec<String>>().join(",");
let stmt = format!("SELECT id, SUM(total) as total WHERE id IN ({}) GROUP BY id", placeholders);
pool.prep_exec(stmt, ids);
...
```
