### ISSUE TITLE
Will this crate be doing any json related support  via serde or rustc_serialize? 

### ISSUE THREAD

**Issue by TheServerAsterisk** [blackbeam/rust-mysql-simple#87]
Since mysql 5.7.7 the JSON data type is now available (I think it was 5.7.7) I was wondering if there will be any support or willingness to have it as crate feature (serde or rustc_serialize) for the FromValue trait? Or would this be a bad idea?

**Comment by blackbeam** [comment]
This is desired for sure, but i know nothing about protocol level implementation of JSON support in MySql at the moment.
I'll investigate it next week.

**Comment by blackbeam** [comment]
Implemented in v9.0.0.
