### ISSUE TITLE
Can't create second pool

### ISSUE THREAD

**Issue by e-oz** [blackbeam/rust-mysql-simple#92]
I'm trying to create second pool (Pool::new), connected to another DB, but when I'm trying to execute query - getting error about non-existing table, and in description of error MySQL gives name of DB - and it's still first DB, not another one.

mysql 9.0.1

**Comment by blackbeam** [comment]
Damn. I think I know why.
Will fix ASAP.

**Comment by blackbeam** [comment]
Problem solved in v10.0.0.
If update is problematic please use solution proposed in previous comment.

Thanks!

**Comment by e-oz** [comment]
@blackbeam works fine, thank you very much!
