### ISSUE TITLE
A good way to bind the rust/mysql boolean to a JSON Boolean?

### ISSUE THREAD

**Issue by TheServerAsterisk** [blackbeam/rust-mysql-simple#95]
Consider an example like: 
```SQL
UPDATE 
    test.mytable 
SET
  some_field  = JSON_REPLACE(some_field, '$.field1', ?, '$.field3', ?)
```
Which updates a subset of fields within the json column. As I am sure you are aware mysql encode booleans as 0 and 1. Accordingly, if one were to bind a boolean to one of the `?` values you get a 0 or a 1 as a field. Unfortunately, serde/rustc will panic as 0 and 1 are not valid json booleans.

There are two solutions I can think of doing: 
1)  Convert the value to a string like so: 
     ```rust
            fn encode_json_boolean(subject: bool) -> String {
                 if subject {
                      "true".to_owned()
                 }
                 else {
                      "false".to_owned()
                 }
            }
      ```
2) impl the FromValue for the serde/rustc json values so one just call `serde/rustc::from_value()`

Within php at very least it seems the trend is to use `json_encode()` which then cast the boolean to a string thus the suggestion to bind the serde and rustc value enums. 

So if it is the former should this crate offer a small convenience function like the one posted? Or is it the user's responsibility to alter it correctly? Either way, I am good, but just wanted your input on the issue.

**Comment by blackbeam** [comment]
I think you just need to pass rustc/serde `Json::Boolean(_)` to a statement.

**Comment by TheServerAsterisk** [comment]
Oh right! I completely forgot that Json was already implemented...
