### ISSUE TITLE
Ability to set bind address for connection

### ISSUE THREAD

**Issue by jonhoo** [blackbeam/rust-mysql-simple#97]
For multi-homed hosts, it would be great to be able to set the preferred bind address on `OptsBuilder`.

**Comment by blackbeam** [comment]
AFAIK bind is used only on server side. Could you please give more details?

**Comment by blackbeam** [comment]
Oh. I see that it's possible to bind before connect.
I'll implement this.

**Comment by jonhoo** [comment]
For what it's worth, I recently implemented this myself elsewhere, and had to use [`net2::TcpBuilder`](https://doc.rust-lang.org/net2-rs/net2/struct.TcpBuilder.html#method.bind). It's a bit annoying, but works.

**Comment by blackbeam** [comment]
available in v11.1.0
